-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_ConvertWeightToStream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_CONV_BUS_AWVALID : OUT STD_LOGIC;
    m_axi_CONV_BUS_AWREADY : IN STD_LOGIC;
    m_axi_CONV_BUS_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_CONV_BUS_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_CONV_BUS_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_CONV_BUS_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_CONV_BUS_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_CONV_BUS_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_CONV_BUS_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_CONV_BUS_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_CONV_BUS_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_CONV_BUS_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_WVALID : OUT STD_LOGIC;
    m_axi_CONV_BUS_WREADY : IN STD_LOGIC;
    m_axi_CONV_BUS_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_CONV_BUS_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_CONV_BUS_WLAST : OUT STD_LOGIC;
    m_axi_CONV_BUS_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_ARVALID : OUT STD_LOGIC;
    m_axi_CONV_BUS_ARREADY : IN STD_LOGIC;
    m_axi_CONV_BUS_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_CONV_BUS_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_CONV_BUS_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_CONV_BUS_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_CONV_BUS_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_CONV_BUS_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_CONV_BUS_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_CONV_BUS_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_CONV_BUS_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_CONV_BUS_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_RVALID : IN STD_LOGIC;
    m_axi_CONV_BUS_RREADY : OUT STD_LOGIC;
    m_axi_CONV_BUS_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_CONV_BUS_RLAST : IN STD_LOGIC;
    m_axi_CONV_BUS_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_CONV_BUS_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_CONV_BUS_BVALID : IN STD_LOGIC;
    m_axi_CONV_BUS_BREADY : OUT STD_LOGIC;
    m_axi_CONV_BUS_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_CONV_BUS_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_CONV_BUS_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    Conv_Weight : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_MM_BUS_AWVALID : OUT STD_LOGIC;
    m_axi_MM_BUS_AWREADY : IN STD_LOGIC;
    m_axi_MM_BUS_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_MM_BUS_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_MM_BUS_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_MM_BUS_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_MM_BUS_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_MM_BUS_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_MM_BUS_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_MM_BUS_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_MM_BUS_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_MM_BUS_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_WVALID : OUT STD_LOGIC;
    m_axi_MM_BUS_WREADY : IN STD_LOGIC;
    m_axi_MM_BUS_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_MM_BUS_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_MM_BUS_WLAST : OUT STD_LOGIC;
    m_axi_MM_BUS_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_ARVALID : OUT STD_LOGIC;
    m_axi_MM_BUS_ARREADY : IN STD_LOGIC;
    m_axi_MM_BUS_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_MM_BUS_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_MM_BUS_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_MM_BUS_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_MM_BUS_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_MM_BUS_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_MM_BUS_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_MM_BUS_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_MM_BUS_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_MM_BUS_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_RVALID : IN STD_LOGIC;
    m_axi_MM_BUS_RREADY : OUT STD_LOGIC;
    m_axi_MM_BUS_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_MM_BUS_RLAST : IN STD_LOGIC;
    m_axi_MM_BUS_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_MM_BUS_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_MM_BUS_BVALID : IN STD_LOGIC;
    m_axi_MM_BUS_BREADY : OUT STD_LOGIC;
    m_axi_MM_BUS_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_MM_BUS_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_MM_BUS_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    MM_Weight : IN STD_LOGIC_VECTOR (63 downto 0);
    fifo_conv_w_0_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    fifo_conv_w_0_full_n : IN STD_LOGIC;
    fifo_conv_w_0_write : OUT STD_LOGIC;
    fifo_conv_w_1_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    fifo_conv_w_1_full_n : IN STD_LOGIC;
    fifo_conv_w_1_write : OUT STD_LOGIC;
    fifo_conv_w_2_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    fifo_conv_w_2_full_n : IN STD_LOGIC;
    fifo_conv_w_2_write : OUT STD_LOGIC;
    fifo_conv_w_3_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    fifo_conv_w_3_full_n : IN STD_LOGIC;
    fifo_conv_w_3_write : OUT STD_LOGIC;
    fifo_mm_w_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    fifo_mm_w_full_n : IN STD_LOGIC;
    fifo_mm_w_write : OUT STD_LOGIC;
    R : IN STD_LOGIC_VECTOR (31 downto 0);
    N : IN STD_LOGIC_VECTOR (31 downto 0);
    K : IN STD_LOGIC_VECTOR (31 downto 0);
    M : IN STD_LOGIC_VECTOR (31 downto 0);
    mode : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of top_ConvertWeightToStream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal mode_read_read_fu_78_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_181_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln_reg_300 : STD_LOGIC_VECTOR (27 downto 0);
    signal bound39_fu_153_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal bound39_reg_305 : STD_LOGIC_VECTOR (59 downto 0);
    signal bound46_fu_157_p2 : STD_LOGIC_VECTOR (87 downto 0);
    signal bound46_reg_310 : STD_LOGIC_VECTOR (87 downto 0);
    signal mul11_fu_169_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul11_reg_315 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_reg_320 : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_326 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal and_ln_fu_236_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal and_ln_reg_331 : STD_LOGIC_VECTOR (29 downto 0);
    signal bound_fu_165_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal bound_reg_337 : STD_LOGIC_VECTOR (61 downto 0);
    signal tmp_s_fu_252_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_reg_342 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound17_fu_161_p2 : STD_LOGIC_VECTOR (91 downto 0);
    signal bound17_reg_347 : STD_LOGIC_VECTOR (91 downto 0);
    signal empty_fu_269_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_reg_352 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_done : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_idle : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_ready : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWVALID : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WVALID : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WLAST : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARVALID : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_RREADY : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_BREADY : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_fifo_mm_w_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_fifo_mm_w_write : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_done : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_idle : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_ready : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWVALID : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WVALID : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WLAST : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARVALID : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_RREADY : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_BREADY : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_2_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_2_write : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_1_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_1_write : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_0_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_0_write : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_3_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_3_write : STD_LOGIC;
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal bound39_fu_153_p0 : STD_LOGIC_VECTOR (27 downto 0);
    signal bound39_fu_153_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound46_fu_157_p0 : STD_LOGIC_VECTOR (27 downto 0);
    signal bound46_fu_157_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal bound17_fu_161_p0 : STD_LOGIC_VECTOR (27 downto 0);
    signal bound17_fu_161_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_fu_165_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_165_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_fu_174_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cast38_fu_206_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal div43_cast_fu_191_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_block_state6_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal bound17_fu_161_p00 : STD_LOGIC_VECTOR (91 downto 0);
    signal bound17_fu_161_p10 : STD_LOGIC_VECTOR (91 downto 0);
    signal bound39_fu_153_p00 : STD_LOGIC_VECTOR (59 downto 0);
    signal bound39_fu_153_p10 : STD_LOGIC_VECTOR (59 downto 0);
    signal bound46_fu_157_p00 : STD_LOGIC_VECTOR (87 downto 0);
    signal bound46_fu_157_p10 : STD_LOGIC_VECTOR (87 downto 0);
    signal bound_fu_165_p00 : STD_LOGIC_VECTOR (61 downto 0);
    signal bound_fu_165_p10 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_MM_BUS_AWVALID : OUT STD_LOGIC;
        m_axi_MM_BUS_AWREADY : IN STD_LOGIC;
        m_axi_MM_BUS_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_MM_BUS_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_MM_BUS_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_MM_BUS_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_MM_BUS_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_MM_BUS_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_MM_BUS_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_MM_BUS_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_MM_BUS_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_MM_BUS_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_WVALID : OUT STD_LOGIC;
        m_axi_MM_BUS_WREADY : IN STD_LOGIC;
        m_axi_MM_BUS_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        m_axi_MM_BUS_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_MM_BUS_WLAST : OUT STD_LOGIC;
        m_axi_MM_BUS_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_ARVALID : OUT STD_LOGIC;
        m_axi_MM_BUS_ARREADY : IN STD_LOGIC;
        m_axi_MM_BUS_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_MM_BUS_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_MM_BUS_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_MM_BUS_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_MM_BUS_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_MM_BUS_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_MM_BUS_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_MM_BUS_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_MM_BUS_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_MM_BUS_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_RVALID : IN STD_LOGIC;
        m_axi_MM_BUS_RREADY : OUT STD_LOGIC;
        m_axi_MM_BUS_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        m_axi_MM_BUS_RLAST : IN STD_LOGIC;
        m_axi_MM_BUS_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_MM_BUS_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_MM_BUS_BVALID : IN STD_LOGIC;
        m_axi_MM_BUS_BREADY : OUT STD_LOGIC;
        m_axi_MM_BUS_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_MM_BUS_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_MM_BUS_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        fifo_mm_w_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        fifo_mm_w_full_n : IN STD_LOGIC;
        fifo_mm_w_write : OUT STD_LOGIC;
        bound46 : IN STD_LOGIC_VECTOR (87 downto 0);
        N : IN STD_LOGIC_VECTOR (31 downto 0);
        bound39 : IN STD_LOGIC_VECTOR (59 downto 0);
        MM_Weight : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component top_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_CONV_BUS_AWVALID : OUT STD_LOGIC;
        m_axi_CONV_BUS_AWREADY : IN STD_LOGIC;
        m_axi_CONV_BUS_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_CONV_BUS_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_CONV_BUS_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_CONV_BUS_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_CONV_BUS_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_CONV_BUS_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_CONV_BUS_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_CONV_BUS_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_CONV_BUS_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_CONV_BUS_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_WVALID : OUT STD_LOGIC;
        m_axi_CONV_BUS_WREADY : IN STD_LOGIC;
        m_axi_CONV_BUS_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        m_axi_CONV_BUS_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_CONV_BUS_WLAST : OUT STD_LOGIC;
        m_axi_CONV_BUS_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_ARVALID : OUT STD_LOGIC;
        m_axi_CONV_BUS_ARREADY : IN STD_LOGIC;
        m_axi_CONV_BUS_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_CONV_BUS_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_CONV_BUS_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_CONV_BUS_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_CONV_BUS_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_CONV_BUS_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_CONV_BUS_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_CONV_BUS_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_CONV_BUS_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_CONV_BUS_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_RVALID : IN STD_LOGIC;
        m_axi_CONV_BUS_RREADY : OUT STD_LOGIC;
        m_axi_CONV_BUS_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        m_axi_CONV_BUS_RLAST : IN STD_LOGIC;
        m_axi_CONV_BUS_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_CONV_BUS_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_CONV_BUS_BVALID : IN STD_LOGIC;
        m_axi_CONV_BUS_BREADY : OUT STD_LOGIC;
        m_axi_CONV_BUS_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_CONV_BUS_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_CONV_BUS_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        fifo_conv_w_2_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        fifo_conv_w_2_full_n : IN STD_LOGIC;
        fifo_conv_w_2_write : OUT STD_LOGIC;
        fifo_conv_w_1_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        fifo_conv_w_1_full_n : IN STD_LOGIC;
        fifo_conv_w_1_write : OUT STD_LOGIC;
        fifo_conv_w_0_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        fifo_conv_w_0_full_n : IN STD_LOGIC;
        fifo_conv_w_0_write : OUT STD_LOGIC;
        fifo_conv_w_3_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        fifo_conv_w_3_full_n : IN STD_LOGIC;
        fifo_conv_w_3_write : OUT STD_LOGIC;
        bound17 : IN STD_LOGIC_VECTOR (91 downto 0);
        zext_ln221 : IN STD_LOGIC_VECTOR (29 downto 0);
        bound4 : IN STD_LOGIC_VECTOR (63 downto 0);
        and_ln : IN STD_LOGIC_VECTOR (29 downto 0);
        bound : IN STD_LOGIC_VECTOR (61 downto 0);
        mul11 : IN STD_LOGIC_VECTOR (31 downto 0);
        Conv_Weight : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component top_mul_28ns_32ns_60_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (59 downto 0) );
    end component;


    component top_mul_28ns_60ns_88_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (59 downto 0);
        dout : OUT STD_LOGIC_VECTOR (87 downto 0) );
    end component;


    component top_mul_28ns_64ns_92_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        dout : OUT STD_LOGIC_VECTOR (91 downto 0) );
    end component;


    component top_mul_32ns_30ns_62_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (29 downto 0);
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component top_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120 : component top_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start,
        ap_done => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_done,
        ap_idle => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_idle,
        ap_ready => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_ready,
        m_axi_MM_BUS_AWVALID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWVALID,
        m_axi_MM_BUS_AWREADY => ap_const_logic_0,
        m_axi_MM_BUS_AWADDR => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWADDR,
        m_axi_MM_BUS_AWID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWID,
        m_axi_MM_BUS_AWLEN => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWLEN,
        m_axi_MM_BUS_AWSIZE => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWSIZE,
        m_axi_MM_BUS_AWBURST => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWBURST,
        m_axi_MM_BUS_AWLOCK => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWLOCK,
        m_axi_MM_BUS_AWCACHE => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWCACHE,
        m_axi_MM_BUS_AWPROT => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWPROT,
        m_axi_MM_BUS_AWQOS => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWQOS,
        m_axi_MM_BUS_AWREGION => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWREGION,
        m_axi_MM_BUS_AWUSER => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_AWUSER,
        m_axi_MM_BUS_WVALID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WVALID,
        m_axi_MM_BUS_WREADY => ap_const_logic_0,
        m_axi_MM_BUS_WDATA => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WDATA,
        m_axi_MM_BUS_WSTRB => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WSTRB,
        m_axi_MM_BUS_WLAST => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WLAST,
        m_axi_MM_BUS_WID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WID,
        m_axi_MM_BUS_WUSER => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_WUSER,
        m_axi_MM_BUS_ARVALID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARVALID,
        m_axi_MM_BUS_ARREADY => m_axi_MM_BUS_ARREADY,
        m_axi_MM_BUS_ARADDR => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARADDR,
        m_axi_MM_BUS_ARID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARID,
        m_axi_MM_BUS_ARLEN => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARLEN,
        m_axi_MM_BUS_ARSIZE => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARSIZE,
        m_axi_MM_BUS_ARBURST => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARBURST,
        m_axi_MM_BUS_ARLOCK => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARLOCK,
        m_axi_MM_BUS_ARCACHE => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARCACHE,
        m_axi_MM_BUS_ARPROT => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARPROT,
        m_axi_MM_BUS_ARQOS => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARQOS,
        m_axi_MM_BUS_ARREGION => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARREGION,
        m_axi_MM_BUS_ARUSER => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARUSER,
        m_axi_MM_BUS_RVALID => m_axi_MM_BUS_RVALID,
        m_axi_MM_BUS_RREADY => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_RREADY,
        m_axi_MM_BUS_RDATA => m_axi_MM_BUS_RDATA,
        m_axi_MM_BUS_RLAST => m_axi_MM_BUS_RLAST,
        m_axi_MM_BUS_RID => m_axi_MM_BUS_RID,
        m_axi_MM_BUS_RFIFONUM => m_axi_MM_BUS_RFIFONUM,
        m_axi_MM_BUS_RUSER => m_axi_MM_BUS_RUSER,
        m_axi_MM_BUS_RRESP => m_axi_MM_BUS_RRESP,
        m_axi_MM_BUS_BVALID => ap_const_logic_0,
        m_axi_MM_BUS_BREADY => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_BREADY,
        m_axi_MM_BUS_BRESP => ap_const_lv2_0,
        m_axi_MM_BUS_BID => ap_const_lv1_0,
        m_axi_MM_BUS_BUSER => ap_const_lv1_0,
        fifo_mm_w_din => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_fifo_mm_w_din,
        fifo_mm_w_full_n => fifo_mm_w_full_n,
        fifo_mm_w_write => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_fifo_mm_w_write,
        bound46 => bound46_reg_310,
        N => N,
        bound39 => bound39_reg_305,
        MM_Weight => MM_Weight);

    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132 : component top_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start,
        ap_done => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_done,
        ap_idle => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_idle,
        ap_ready => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_ready,
        m_axi_CONV_BUS_AWVALID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWVALID,
        m_axi_CONV_BUS_AWREADY => ap_const_logic_0,
        m_axi_CONV_BUS_AWADDR => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWADDR,
        m_axi_CONV_BUS_AWID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWID,
        m_axi_CONV_BUS_AWLEN => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWLEN,
        m_axi_CONV_BUS_AWSIZE => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWSIZE,
        m_axi_CONV_BUS_AWBURST => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWBURST,
        m_axi_CONV_BUS_AWLOCK => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWLOCK,
        m_axi_CONV_BUS_AWCACHE => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWCACHE,
        m_axi_CONV_BUS_AWPROT => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWPROT,
        m_axi_CONV_BUS_AWQOS => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWQOS,
        m_axi_CONV_BUS_AWREGION => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWREGION,
        m_axi_CONV_BUS_AWUSER => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_AWUSER,
        m_axi_CONV_BUS_WVALID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WVALID,
        m_axi_CONV_BUS_WREADY => ap_const_logic_0,
        m_axi_CONV_BUS_WDATA => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WDATA,
        m_axi_CONV_BUS_WSTRB => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WSTRB,
        m_axi_CONV_BUS_WLAST => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WLAST,
        m_axi_CONV_BUS_WID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WID,
        m_axi_CONV_BUS_WUSER => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_WUSER,
        m_axi_CONV_BUS_ARVALID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARVALID,
        m_axi_CONV_BUS_ARREADY => m_axi_CONV_BUS_ARREADY,
        m_axi_CONV_BUS_ARADDR => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARADDR,
        m_axi_CONV_BUS_ARID => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARID,
        m_axi_CONV_BUS_ARLEN => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARLEN,
        m_axi_CONV_BUS_ARSIZE => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARSIZE,
        m_axi_CONV_BUS_ARBURST => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARBURST,
        m_axi_CONV_BUS_ARLOCK => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARLOCK,
        m_axi_CONV_BUS_ARCACHE => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARCACHE,
        m_axi_CONV_BUS_ARPROT => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARPROT,
        m_axi_CONV_BUS_ARQOS => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARQOS,
        m_axi_CONV_BUS_ARREGION => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARREGION,
        m_axi_CONV_BUS_ARUSER => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARUSER,
        m_axi_CONV_BUS_RVALID => m_axi_CONV_BUS_RVALID,
        m_axi_CONV_BUS_RREADY => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_RREADY,
        m_axi_CONV_BUS_RDATA => m_axi_CONV_BUS_RDATA,
        m_axi_CONV_BUS_RLAST => m_axi_CONV_BUS_RLAST,
        m_axi_CONV_BUS_RID => m_axi_CONV_BUS_RID,
        m_axi_CONV_BUS_RFIFONUM => m_axi_CONV_BUS_RFIFONUM,
        m_axi_CONV_BUS_RUSER => m_axi_CONV_BUS_RUSER,
        m_axi_CONV_BUS_RRESP => m_axi_CONV_BUS_RRESP,
        m_axi_CONV_BUS_BVALID => ap_const_logic_0,
        m_axi_CONV_BUS_BREADY => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_BREADY,
        m_axi_CONV_BUS_BRESP => ap_const_lv2_0,
        m_axi_CONV_BUS_BID => ap_const_lv1_0,
        m_axi_CONV_BUS_BUSER => ap_const_lv1_0,
        fifo_conv_w_2_din => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_2_din,
        fifo_conv_w_2_full_n => fifo_conv_w_2_full_n,
        fifo_conv_w_2_write => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_2_write,
        fifo_conv_w_1_din => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_1_din,
        fifo_conv_w_1_full_n => fifo_conv_w_1_full_n,
        fifo_conv_w_1_write => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_1_write,
        fifo_conv_w_0_din => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_0_din,
        fifo_conv_w_0_full_n => fifo_conv_w_0_full_n,
        fifo_conv_w_0_write => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_0_write,
        fifo_conv_w_3_din => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_3_din,
        fifo_conv_w_3_full_n => fifo_conv_w_3_full_n,
        fifo_conv_w_3_write => grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_3_write,
        bound17 => bound17_reg_347,
        zext_ln221 => empty_reg_352,
        bound4 => tmp_s_reg_342,
        and_ln => and_ln_reg_331,
        bound => bound_reg_337,
        mul11 => mul11_reg_315,
        Conv_Weight => Conv_Weight);

    mul_28ns_32ns_60_1_1_U105 : component top_mul_28ns_32ns_60_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 32,
        dout_WIDTH => 60)
    port map (
        din0 => bound39_fu_153_p0,
        din1 => bound39_fu_153_p1,
        dout => bound39_fu_153_p2);

    mul_28ns_60ns_88_1_1_U106 : component top_mul_28ns_60ns_88_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 60,
        dout_WIDTH => 88)
    port map (
        din0 => bound46_fu_157_p0,
        din1 => bound46_fu_157_p1,
        dout => bound46_fu_157_p2);

    mul_28ns_64ns_92_1_1_U107 : component top_mul_28ns_64ns_92_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 64,
        dout_WIDTH => 92)
    port map (
        din0 => bound17_fu_161_p0,
        din1 => bound17_fu_161_p1,
        dout => bound17_fu_161_p2);

    mul_32ns_30ns_62_1_1_U108 : component top_mul_32ns_30ns_62_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 30,
        dout_WIDTH => 62)
    port map (
        din0 => bound_fu_165_p0,
        din1 => bound_fu_165_p1,
        dout => bound_fu_165_p2);

    mul_32s_32s_32_1_1_U109 : component top_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_fu_174_p2,
        din1 => K,
        dout => mul11_fu_169_p2);

    mul_32s_32s_32_1_1_U110 : component top_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => K,
        din1 => N,
        dout => tmp_fu_174_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_ready = ap_const_logic_1)) then 
                    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_ready = ap_const_logic_1)) then 
                    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                    and_ln_reg_331(29 downto 2) <= and_ln_fu_236_p3(29 downto 2);
                bound17_reg_347 <= bound17_fu_161_p2;
                bound_reg_337 <= bound_fu_165_p2;
                icmp_reg_326 <= icmp_fu_231_p2;
                    tmp_s_reg_342(63 downto 2) <= tmp_s_fu_252_p3(63 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                bound39_reg_305 <= bound39_fu_153_p2;
                bound46_reg_310 <= bound46_fu_157_p2;
                mul11_reg_315 <= mul11_fu_169_p2;
                tmp_25_reg_320 <= mul11_fu_169_p2(31 downto 4);
                trunc_ln_reg_300 <= M(31 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    empty_reg_352(29 downto 2) <= empty_fu_269_p3(29 downto 2);
            end if;
        end if;
    end process;
    and_ln_reg_331(1 downto 0) <= "00";
    tmp_s_reg_342(1 downto 0) <= "00";
    empty_reg_352(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, mode, mode_read_read_fu_78_p2, grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_block_state6_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (mode = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (mode_read_read_fu_78_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    and_ln_fu_236_p3 <= (tmp_25_reg_320 & ap_const_lv2_0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_done)
    begin
        if ((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state6_on_subcall_done)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state6_on_subcall_done_assign_proc : process(mode, grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_done)
    begin
                ap_block_state6_on_subcall_done <= ((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_done = ap_const_logic_0) and (mode = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state6, ap_block_state6_on_subcall_done)
    begin
        if ((((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, ap_block_state6_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound17_fu_161_p0 <= bound17_fu_161_p00(28 - 1 downto 0);
    bound17_fu_161_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln_reg_300),92));
    bound17_fu_161_p1 <= bound17_fu_161_p10(64 - 1 downto 0);
    bound17_fu_161_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_252_p3),92));
    bound39_fu_153_p0 <= bound39_fu_153_p00(28 - 1 downto 0);
    bound39_fu_153_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln_fu_181_p4),60));
    bound39_fu_153_p1 <= bound39_fu_153_p10(32 - 1 downto 0);
    bound39_fu_153_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cast38_fu_206_p0),60));
    bound46_fu_157_p0 <= bound46_fu_157_p00(28 - 1 downto 0);
    bound46_fu_157_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div43_cast_fu_191_p4),88));
    bound46_fu_157_p1 <= bound46_fu_157_p10(60 - 1 downto 0);
    bound46_fu_157_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bound39_fu_153_p2),88));
    bound_fu_165_p0 <= bound_fu_165_p00(32 - 1 downto 0);
    bound_fu_165_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(R),62));
    bound_fu_165_p1 <= bound_fu_165_p10(30 - 1 downto 0);
    bound_fu_165_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln_fu_236_p3),62));
    cast38_fu_206_p0 <= N;
    div43_cast_fu_191_p4 <= R(31 downto 4);
    empty_fu_269_p3 <= 
        and_ln_reg_331 when (icmp_reg_326(0) = '1') else 
        ap_const_lv30_0;
    fifo_conv_w_0_din <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_0_din;

    fifo_conv_w_0_write_assign_proc : process(mode, grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_0_write, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (mode = ap_const_lv1_1))) then 
            fifo_conv_w_0_write <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_0_write;
        else 
            fifo_conv_w_0_write <= ap_const_logic_0;
        end if; 
    end process;

    fifo_conv_w_1_din <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_1_din;

    fifo_conv_w_1_write_assign_proc : process(mode, grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_1_write, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (mode = ap_const_lv1_1))) then 
            fifo_conv_w_1_write <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_1_write;
        else 
            fifo_conv_w_1_write <= ap_const_logic_0;
        end if; 
    end process;

    fifo_conv_w_2_din <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_2_din;

    fifo_conv_w_2_write_assign_proc : process(mode, grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_2_write, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (mode = ap_const_lv1_1))) then 
            fifo_conv_w_2_write <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_2_write;
        else 
            fifo_conv_w_2_write <= ap_const_logic_0;
        end if; 
    end process;

    fifo_conv_w_3_din <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_3_din;

    fifo_conv_w_3_write_assign_proc : process(mode, grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_3_write, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (mode = ap_const_lv1_1))) then 
            fifo_conv_w_3_write <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_fifo_conv_w_3_write;
        else 
            fifo_conv_w_3_write <= ap_const_logic_0;
        end if; 
    end process;

    fifo_mm_w_din <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_fifo_mm_w_din;

    fifo_mm_w_write_assign_proc : process(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_fifo_mm_w_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fifo_mm_w_write <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_fifo_mm_w_write;
        else 
            fifo_mm_w_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_ap_start_reg;
    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_ap_start_reg;
    icmp_fu_231_p2 <= "0" when (tmp_25_reg_320 = ap_const_lv28_0) else "1";
    m_axi_CONV_BUS_ARADDR <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARADDR;
    m_axi_CONV_BUS_ARBURST <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARBURST;
    m_axi_CONV_BUS_ARCACHE <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARCACHE;
    m_axi_CONV_BUS_ARID <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARID;
    m_axi_CONV_BUS_ARLEN <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARLEN;
    m_axi_CONV_BUS_ARLOCK <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARLOCK;
    m_axi_CONV_BUS_ARPROT <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARPROT;
    m_axi_CONV_BUS_ARQOS <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARQOS;
    m_axi_CONV_BUS_ARREGION <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARREGION;
    m_axi_CONV_BUS_ARSIZE <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARSIZE;
    m_axi_CONV_BUS_ARUSER <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARUSER;

    m_axi_CONV_BUS_ARVALID_assign_proc : process(mode, ap_CS_fsm_state5, grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARVALID, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (mode = ap_const_lv1_1)))) then 
            m_axi_CONV_BUS_ARVALID <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_ARVALID;
        else 
            m_axi_CONV_BUS_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_CONV_BUS_AWADDR <= ap_const_lv64_0;
    m_axi_CONV_BUS_AWBURST <= ap_const_lv2_0;
    m_axi_CONV_BUS_AWCACHE <= ap_const_lv4_0;
    m_axi_CONV_BUS_AWID <= ap_const_lv1_0;
    m_axi_CONV_BUS_AWLEN <= ap_const_lv32_0;
    m_axi_CONV_BUS_AWLOCK <= ap_const_lv2_0;
    m_axi_CONV_BUS_AWPROT <= ap_const_lv3_0;
    m_axi_CONV_BUS_AWQOS <= ap_const_lv4_0;
    m_axi_CONV_BUS_AWREGION <= ap_const_lv4_0;
    m_axi_CONV_BUS_AWSIZE <= ap_const_lv3_0;
    m_axi_CONV_BUS_AWUSER <= ap_const_lv1_0;
    m_axi_CONV_BUS_AWVALID <= ap_const_logic_0;
    m_axi_CONV_BUS_BREADY <= ap_const_logic_0;

    m_axi_CONV_BUS_RREADY_assign_proc : process(mode, ap_CS_fsm_state5, grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_RREADY, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (mode = ap_const_lv1_1)))) then 
            m_axi_CONV_BUS_RREADY <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_221_1_VITIS_LOOP_224_2_VITIS_LOOP_226_s_fu_132_m_axi_CONV_BUS_RREADY;
        else 
            m_axi_CONV_BUS_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_CONV_BUS_WDATA <= ap_const_lv128_lc_1;
    m_axi_CONV_BUS_WID <= ap_const_lv1_0;
    m_axi_CONV_BUS_WLAST <= ap_const_logic_0;
    m_axi_CONV_BUS_WSTRB <= ap_const_lv16_0;
    m_axi_CONV_BUS_WUSER <= ap_const_lv1_0;
    m_axi_CONV_BUS_WVALID <= ap_const_logic_0;
    m_axi_MM_BUS_ARADDR <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARADDR;
    m_axi_MM_BUS_ARBURST <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARBURST;
    m_axi_MM_BUS_ARCACHE <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARCACHE;
    m_axi_MM_BUS_ARID <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARID;
    m_axi_MM_BUS_ARLEN <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARLEN;
    m_axi_MM_BUS_ARLOCK <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARLOCK;
    m_axi_MM_BUS_ARPROT <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARPROT;
    m_axi_MM_BUS_ARQOS <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARQOS;
    m_axi_MM_BUS_ARREGION <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARREGION;
    m_axi_MM_BUS_ARSIZE <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARSIZE;
    m_axi_MM_BUS_ARUSER <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARUSER;

    m_axi_MM_BUS_ARVALID_assign_proc : process(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARVALID, ap_CS_fsm_state3, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_MM_BUS_ARVALID <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_ARVALID;
        else 
            m_axi_MM_BUS_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_MM_BUS_AWADDR <= ap_const_lv64_0;
    m_axi_MM_BUS_AWBURST <= ap_const_lv2_0;
    m_axi_MM_BUS_AWCACHE <= ap_const_lv4_0;
    m_axi_MM_BUS_AWID <= ap_const_lv1_0;
    m_axi_MM_BUS_AWLEN <= ap_const_lv32_0;
    m_axi_MM_BUS_AWLOCK <= ap_const_lv2_0;
    m_axi_MM_BUS_AWPROT <= ap_const_lv3_0;
    m_axi_MM_BUS_AWQOS <= ap_const_lv4_0;
    m_axi_MM_BUS_AWREGION <= ap_const_lv4_0;
    m_axi_MM_BUS_AWSIZE <= ap_const_lv3_0;
    m_axi_MM_BUS_AWUSER <= ap_const_lv1_0;
    m_axi_MM_BUS_AWVALID <= ap_const_logic_0;
    m_axi_MM_BUS_BREADY <= ap_const_logic_0;

    m_axi_MM_BUS_RREADY_assign_proc : process(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_RREADY, ap_CS_fsm_state3, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_MM_BUS_RREADY <= grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_243_5_VITIS_LOOP_246_6_VITIS_LOOP_249_s_fu_120_m_axi_MM_BUS_RREADY;
        else 
            m_axi_MM_BUS_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_MM_BUS_WDATA <= ap_const_lv128_lc_1;
    m_axi_MM_BUS_WID <= ap_const_lv1_0;
    m_axi_MM_BUS_WLAST <= ap_const_logic_0;
    m_axi_MM_BUS_WSTRB <= ap_const_lv16_0;
    m_axi_MM_BUS_WUSER <= ap_const_lv1_0;
    m_axi_MM_BUS_WVALID <= ap_const_logic_0;
    mode_read_read_fu_78_p2 <= mode;
    tmp_s_fu_252_p3 <= (bound_fu_165_p2 & ap_const_lv2_0);
    trunc_ln_fu_181_p4 <= M(31 downto 4);
end behav;
