// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_ConvertWeightToStream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_CONV_BUS_AWVALID,
        m_axi_CONV_BUS_AWREADY,
        m_axi_CONV_BUS_AWADDR,
        m_axi_CONV_BUS_AWID,
        m_axi_CONV_BUS_AWLEN,
        m_axi_CONV_BUS_AWSIZE,
        m_axi_CONV_BUS_AWBURST,
        m_axi_CONV_BUS_AWLOCK,
        m_axi_CONV_BUS_AWCACHE,
        m_axi_CONV_BUS_AWPROT,
        m_axi_CONV_BUS_AWQOS,
        m_axi_CONV_BUS_AWREGION,
        m_axi_CONV_BUS_AWUSER,
        m_axi_CONV_BUS_WVALID,
        m_axi_CONV_BUS_WREADY,
        m_axi_CONV_BUS_WDATA,
        m_axi_CONV_BUS_WSTRB,
        m_axi_CONV_BUS_WLAST,
        m_axi_CONV_BUS_WID,
        m_axi_CONV_BUS_WUSER,
        m_axi_CONV_BUS_ARVALID,
        m_axi_CONV_BUS_ARREADY,
        m_axi_CONV_BUS_ARADDR,
        m_axi_CONV_BUS_ARID,
        m_axi_CONV_BUS_ARLEN,
        m_axi_CONV_BUS_ARSIZE,
        m_axi_CONV_BUS_ARBURST,
        m_axi_CONV_BUS_ARLOCK,
        m_axi_CONV_BUS_ARCACHE,
        m_axi_CONV_BUS_ARPROT,
        m_axi_CONV_BUS_ARQOS,
        m_axi_CONV_BUS_ARREGION,
        m_axi_CONV_BUS_ARUSER,
        m_axi_CONV_BUS_RVALID,
        m_axi_CONV_BUS_RREADY,
        m_axi_CONV_BUS_RDATA,
        m_axi_CONV_BUS_RLAST,
        m_axi_CONV_BUS_RID,
        m_axi_CONV_BUS_RFIFONUM,
        m_axi_CONV_BUS_RUSER,
        m_axi_CONV_BUS_RRESP,
        m_axi_CONV_BUS_BVALID,
        m_axi_CONV_BUS_BREADY,
        m_axi_CONV_BUS_BRESP,
        m_axi_CONV_BUS_BID,
        m_axi_CONV_BUS_BUSER,
        Conv_Weight,
        m_axi_MM_BUS_AWVALID,
        m_axi_MM_BUS_AWREADY,
        m_axi_MM_BUS_AWADDR,
        m_axi_MM_BUS_AWID,
        m_axi_MM_BUS_AWLEN,
        m_axi_MM_BUS_AWSIZE,
        m_axi_MM_BUS_AWBURST,
        m_axi_MM_BUS_AWLOCK,
        m_axi_MM_BUS_AWCACHE,
        m_axi_MM_BUS_AWPROT,
        m_axi_MM_BUS_AWQOS,
        m_axi_MM_BUS_AWREGION,
        m_axi_MM_BUS_AWUSER,
        m_axi_MM_BUS_WVALID,
        m_axi_MM_BUS_WREADY,
        m_axi_MM_BUS_WDATA,
        m_axi_MM_BUS_WSTRB,
        m_axi_MM_BUS_WLAST,
        m_axi_MM_BUS_WID,
        m_axi_MM_BUS_WUSER,
        m_axi_MM_BUS_ARVALID,
        m_axi_MM_BUS_ARREADY,
        m_axi_MM_BUS_ARADDR,
        m_axi_MM_BUS_ARID,
        m_axi_MM_BUS_ARLEN,
        m_axi_MM_BUS_ARSIZE,
        m_axi_MM_BUS_ARBURST,
        m_axi_MM_BUS_ARLOCK,
        m_axi_MM_BUS_ARCACHE,
        m_axi_MM_BUS_ARPROT,
        m_axi_MM_BUS_ARQOS,
        m_axi_MM_BUS_ARREGION,
        m_axi_MM_BUS_ARUSER,
        m_axi_MM_BUS_RVALID,
        m_axi_MM_BUS_RREADY,
        m_axi_MM_BUS_RDATA,
        m_axi_MM_BUS_RLAST,
        m_axi_MM_BUS_RID,
        m_axi_MM_BUS_RFIFONUM,
        m_axi_MM_BUS_RUSER,
        m_axi_MM_BUS_RRESP,
        m_axi_MM_BUS_BVALID,
        m_axi_MM_BUS_BREADY,
        m_axi_MM_BUS_BRESP,
        m_axi_MM_BUS_BID,
        m_axi_MM_BUS_BUSER,
        MM_Weight,
        fifo_conv_w_0_din,
        fifo_conv_w_0_num_data_valid,
        fifo_conv_w_0_fifo_cap,
        fifo_conv_w_0_full_n,
        fifo_conv_w_0_write,
        fifo_conv_w_1_din,
        fifo_conv_w_1_num_data_valid,
        fifo_conv_w_1_fifo_cap,
        fifo_conv_w_1_full_n,
        fifo_conv_w_1_write,
        fifo_conv_w_2_din,
        fifo_conv_w_2_num_data_valid,
        fifo_conv_w_2_fifo_cap,
        fifo_conv_w_2_full_n,
        fifo_conv_w_2_write,
        fifo_conv_w_3_din,
        fifo_conv_w_3_num_data_valid,
        fifo_conv_w_3_fifo_cap,
        fifo_conv_w_3_full_n,
        fifo_conv_w_3_write,
        fifo_mm_w_din,
        fifo_mm_w_num_data_valid,
        fifo_mm_w_fifo_cap,
        fifo_mm_w_full_n,
        fifo_mm_w_write,
        R,
        N,
        K,
        M,
        P,
        S,
        mode,
        mode_c68_din,
        mode_c68_num_data_valid,
        mode_c68_fifo_cap,
        mode_c68_full_n,
        mode_c68_write,
        mode_c69_din,
        mode_c69_num_data_valid,
        mode_c69_fifo_cap,
        mode_c69_full_n,
        mode_c69_write
);

parameter    ap_ST_fsm_state1 = 41'd1;
parameter    ap_ST_fsm_state2 = 41'd2;
parameter    ap_ST_fsm_state3 = 41'd4;
parameter    ap_ST_fsm_state4 = 41'd8;
parameter    ap_ST_fsm_state5 = 41'd16;
parameter    ap_ST_fsm_state6 = 41'd32;
parameter    ap_ST_fsm_state7 = 41'd64;
parameter    ap_ST_fsm_state8 = 41'd128;
parameter    ap_ST_fsm_state9 = 41'd256;
parameter    ap_ST_fsm_state10 = 41'd512;
parameter    ap_ST_fsm_state11 = 41'd1024;
parameter    ap_ST_fsm_state12 = 41'd2048;
parameter    ap_ST_fsm_state13 = 41'd4096;
parameter    ap_ST_fsm_state14 = 41'd8192;
parameter    ap_ST_fsm_state15 = 41'd16384;
parameter    ap_ST_fsm_state16 = 41'd32768;
parameter    ap_ST_fsm_state17 = 41'd65536;
parameter    ap_ST_fsm_state18 = 41'd131072;
parameter    ap_ST_fsm_state19 = 41'd262144;
parameter    ap_ST_fsm_state20 = 41'd524288;
parameter    ap_ST_fsm_state21 = 41'd1048576;
parameter    ap_ST_fsm_state22 = 41'd2097152;
parameter    ap_ST_fsm_state23 = 41'd4194304;
parameter    ap_ST_fsm_state24 = 41'd8388608;
parameter    ap_ST_fsm_state25 = 41'd16777216;
parameter    ap_ST_fsm_state26 = 41'd33554432;
parameter    ap_ST_fsm_state27 = 41'd67108864;
parameter    ap_ST_fsm_state28 = 41'd134217728;
parameter    ap_ST_fsm_state29 = 41'd268435456;
parameter    ap_ST_fsm_state30 = 41'd536870912;
parameter    ap_ST_fsm_state31 = 41'd1073741824;
parameter    ap_ST_fsm_state32 = 41'd2147483648;
parameter    ap_ST_fsm_state33 = 41'd4294967296;
parameter    ap_ST_fsm_state34 = 41'd8589934592;
parameter    ap_ST_fsm_state35 = 41'd17179869184;
parameter    ap_ST_fsm_state36 = 41'd34359738368;
parameter    ap_ST_fsm_state37 = 41'd68719476736;
parameter    ap_ST_fsm_state38 = 41'd137438953472;
parameter    ap_ST_fsm_state39 = 41'd274877906944;
parameter    ap_ST_fsm_state40 = 41'd549755813888;
parameter    ap_ST_fsm_state41 = 41'd1099511627776;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_CONV_BUS_AWVALID;
input   m_axi_CONV_BUS_AWREADY;
output  [63:0] m_axi_CONV_BUS_AWADDR;
output  [0:0] m_axi_CONV_BUS_AWID;
output  [31:0] m_axi_CONV_BUS_AWLEN;
output  [2:0] m_axi_CONV_BUS_AWSIZE;
output  [1:0] m_axi_CONV_BUS_AWBURST;
output  [1:0] m_axi_CONV_BUS_AWLOCK;
output  [3:0] m_axi_CONV_BUS_AWCACHE;
output  [2:0] m_axi_CONV_BUS_AWPROT;
output  [3:0] m_axi_CONV_BUS_AWQOS;
output  [3:0] m_axi_CONV_BUS_AWREGION;
output  [0:0] m_axi_CONV_BUS_AWUSER;
output   m_axi_CONV_BUS_WVALID;
input   m_axi_CONV_BUS_WREADY;
output  [511:0] m_axi_CONV_BUS_WDATA;
output  [63:0] m_axi_CONV_BUS_WSTRB;
output   m_axi_CONV_BUS_WLAST;
output  [0:0] m_axi_CONV_BUS_WID;
output  [0:0] m_axi_CONV_BUS_WUSER;
output   m_axi_CONV_BUS_ARVALID;
input   m_axi_CONV_BUS_ARREADY;
output  [63:0] m_axi_CONV_BUS_ARADDR;
output  [0:0] m_axi_CONV_BUS_ARID;
output  [31:0] m_axi_CONV_BUS_ARLEN;
output  [2:0] m_axi_CONV_BUS_ARSIZE;
output  [1:0] m_axi_CONV_BUS_ARBURST;
output  [1:0] m_axi_CONV_BUS_ARLOCK;
output  [3:0] m_axi_CONV_BUS_ARCACHE;
output  [2:0] m_axi_CONV_BUS_ARPROT;
output  [3:0] m_axi_CONV_BUS_ARQOS;
output  [3:0] m_axi_CONV_BUS_ARREGION;
output  [0:0] m_axi_CONV_BUS_ARUSER;
input   m_axi_CONV_BUS_RVALID;
output   m_axi_CONV_BUS_RREADY;
input  [511:0] m_axi_CONV_BUS_RDATA;
input   m_axi_CONV_BUS_RLAST;
input  [0:0] m_axi_CONV_BUS_RID;
input  [8:0] m_axi_CONV_BUS_RFIFONUM;
input  [0:0] m_axi_CONV_BUS_RUSER;
input  [1:0] m_axi_CONV_BUS_RRESP;
input   m_axi_CONV_BUS_BVALID;
output   m_axi_CONV_BUS_BREADY;
input  [1:0] m_axi_CONV_BUS_BRESP;
input  [0:0] m_axi_CONV_BUS_BID;
input  [0:0] m_axi_CONV_BUS_BUSER;
input  [63:0] Conv_Weight;
output   m_axi_MM_BUS_AWVALID;
input   m_axi_MM_BUS_AWREADY;
output  [63:0] m_axi_MM_BUS_AWADDR;
output  [0:0] m_axi_MM_BUS_AWID;
output  [31:0] m_axi_MM_BUS_AWLEN;
output  [2:0] m_axi_MM_BUS_AWSIZE;
output  [1:0] m_axi_MM_BUS_AWBURST;
output  [1:0] m_axi_MM_BUS_AWLOCK;
output  [3:0] m_axi_MM_BUS_AWCACHE;
output  [2:0] m_axi_MM_BUS_AWPROT;
output  [3:0] m_axi_MM_BUS_AWQOS;
output  [3:0] m_axi_MM_BUS_AWREGION;
output  [0:0] m_axi_MM_BUS_AWUSER;
output   m_axi_MM_BUS_WVALID;
input   m_axi_MM_BUS_WREADY;
output  [511:0] m_axi_MM_BUS_WDATA;
output  [63:0] m_axi_MM_BUS_WSTRB;
output   m_axi_MM_BUS_WLAST;
output  [0:0] m_axi_MM_BUS_WID;
output  [0:0] m_axi_MM_BUS_WUSER;
output   m_axi_MM_BUS_ARVALID;
input   m_axi_MM_BUS_ARREADY;
output  [63:0] m_axi_MM_BUS_ARADDR;
output  [0:0] m_axi_MM_BUS_ARID;
output  [31:0] m_axi_MM_BUS_ARLEN;
output  [2:0] m_axi_MM_BUS_ARSIZE;
output  [1:0] m_axi_MM_BUS_ARBURST;
output  [1:0] m_axi_MM_BUS_ARLOCK;
output  [3:0] m_axi_MM_BUS_ARCACHE;
output  [2:0] m_axi_MM_BUS_ARPROT;
output  [3:0] m_axi_MM_BUS_ARQOS;
output  [3:0] m_axi_MM_BUS_ARREGION;
output  [0:0] m_axi_MM_BUS_ARUSER;
input   m_axi_MM_BUS_RVALID;
output   m_axi_MM_BUS_RREADY;
input  [511:0] m_axi_MM_BUS_RDATA;
input   m_axi_MM_BUS_RLAST;
input  [0:0] m_axi_MM_BUS_RID;
input  [8:0] m_axi_MM_BUS_RFIFONUM;
input  [0:0] m_axi_MM_BUS_RUSER;
input  [1:0] m_axi_MM_BUS_RRESP;
input   m_axi_MM_BUS_BVALID;
output   m_axi_MM_BUS_BREADY;
input  [1:0] m_axi_MM_BUS_BRESP;
input  [0:0] m_axi_MM_BUS_BID;
input  [0:0] m_axi_MM_BUS_BUSER;
input  [63:0] MM_Weight;
output  [511:0] fifo_conv_w_0_din;
input  [3:0] fifo_conv_w_0_num_data_valid;
input  [3:0] fifo_conv_w_0_fifo_cap;
input   fifo_conv_w_0_full_n;
output   fifo_conv_w_0_write;
output  [511:0] fifo_conv_w_1_din;
input  [3:0] fifo_conv_w_1_num_data_valid;
input  [3:0] fifo_conv_w_1_fifo_cap;
input   fifo_conv_w_1_full_n;
output   fifo_conv_w_1_write;
output  [511:0] fifo_conv_w_2_din;
input  [3:0] fifo_conv_w_2_num_data_valid;
input  [3:0] fifo_conv_w_2_fifo_cap;
input   fifo_conv_w_2_full_n;
output   fifo_conv_w_2_write;
output  [511:0] fifo_conv_w_3_din;
input  [3:0] fifo_conv_w_3_num_data_valid;
input  [3:0] fifo_conv_w_3_fifo_cap;
input   fifo_conv_w_3_full_n;
output   fifo_conv_w_3_write;
output  [511:0] fifo_mm_w_din;
input  [7:0] fifo_mm_w_num_data_valid;
input  [7:0] fifo_mm_w_fifo_cap;
input   fifo_mm_w_full_n;
output   fifo_mm_w_write;
input  [31:0] R;
input  [31:0] N;
input  [31:0] K;
input  [31:0] M;
input  [31:0] P;
input  [31:0] S;
input  [0:0] mode;
output  [0:0] mode_c68_din;
input  [2:0] mode_c68_num_data_valid;
input  [2:0] mode_c68_fifo_cap;
input   mode_c68_full_n;
output   mode_c68_write;
output  [0:0] mode_c69_din;
input  [2:0] mode_c69_num_data_valid;
input  [2:0] mode_c69_fifo_cap;
input   mode_c69_full_n;
output   mode_c69_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_CONV_BUS_ARVALID;
reg m_axi_CONV_BUS_RREADY;
reg m_axi_MM_BUS_ARVALID;
reg m_axi_MM_BUS_RREADY;
reg fifo_conv_w_0_write;
reg fifo_conv_w_1_write;
reg fifo_conv_w_2_write;
reg fifo_conv_w_3_write;
reg fifo_mm_w_write;
reg mode_c68_write;
reg mode_c69_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [40:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    mode_c68_blk_n;
reg    mode_c69_blk_n;
wire   [0:0] mode_read_read_fu_98_p2;
reg    ap_block_state1;
wire   [27:0] trunc_ln_fu_226_p4;
reg   [27:0] trunc_ln_reg_382;
wire   [59:0] bound39_fu_201_p2;
reg   [59:0] bound39_reg_387;
wire   [87:0] bound46_fu_205_p2;
reg   [87:0] bound46_reg_392;
wire   [31:0] mul14_fu_217_p2;
reg   [31:0] mul14_reg_402;
wire    ap_CS_fsm_state4;
reg   [27:0] tmp_12_reg_407;
wire   [31:0] add8_fu_300_p2;
reg   [31:0] add8_reg_413;
wire    ap_CS_fsm_state38;
wire   [0:0] icmp_fu_306_p2;
reg   [0:0] icmp_reg_418;
wire    ap_CS_fsm_state39;
wire   [29:0] and_ln_fu_311_p3;
reg   [29:0] and_ln_reg_423;
wire   [61:0] bound_fu_213_p2;
reg   [61:0] bound_reg_429;
wire   [63:0] tmp_s_fu_327_p3;
reg   [63:0] tmp_s_reg_434;
wire   [91:0] bound17_fu_209_p2;
reg   [91:0] bound17_reg_439;
wire   [29:0] empty_1053_fu_344_p3;
reg   [29:0] empty_1053_reg_444;
wire    ap_CS_fsm_state40;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_done;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_idle;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_ready;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWVALID;
wire   [63:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWADDR;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWID;
wire   [31:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWLEN;
wire   [2:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWSIZE;
wire   [1:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWBURST;
wire   [1:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWLOCK;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWCACHE;
wire   [2:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWPROT;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWQOS;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWREGION;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWUSER;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WVALID;
wire   [511:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WDATA;
wire   [63:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WSTRB;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WLAST;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WID;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WUSER;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARVALID;
wire   [63:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARADDR;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARID;
wire   [31:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARLEN;
wire   [2:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARSIZE;
wire   [1:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARBURST;
wire   [1:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARLOCK;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARCACHE;
wire   [2:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARPROT;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARQOS;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARREGION;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARUSER;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_RREADY;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_BREADY;
wire   [511:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_fifo_mm_w_din;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_fifo_mm_w_write;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_done;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_idle;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_ready;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWVALID;
wire   [63:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWADDR;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWID;
wire   [31:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWLEN;
wire   [2:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWSIZE;
wire   [1:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWBURST;
wire   [1:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWLOCK;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWCACHE;
wire   [2:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWPROT;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWQOS;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWREGION;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWUSER;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WVALID;
wire   [511:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WDATA;
wire   [63:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WSTRB;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WLAST;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WID;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WUSER;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARVALID;
wire   [63:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARADDR;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARID;
wire   [31:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARLEN;
wire   [2:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARSIZE;
wire   [1:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARBURST;
wire   [1:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARLOCK;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARCACHE;
wire   [2:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARPROT;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARQOS;
wire   [3:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARREGION;
wire   [0:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARUSER;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_RREADY;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_BREADY;
wire   [511:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_2_din;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_2_write;
wire   [511:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_1_din;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_1_write;
wire   [511:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_0_din;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_0_write;
wire   [511:0] grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_3_din;
wire    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_3_write;
reg    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start_reg;
reg   [40:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state2;
reg    grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start_reg;
wire    ap_CS_fsm_state41;
wire   [27:0] bound39_fu_201_p0;
wire   [31:0] bound39_fu_201_p1;
wire   [27:0] bound46_fu_205_p0;
wire   [59:0] bound46_fu_205_p1;
wire   [27:0] bound17_fu_209_p0;
wire   [63:0] bound17_fu_209_p1;
wire   [31:0] bound_fu_213_p0;
wire   [29:0] bound_fu_213_p1;
wire  signed [31:0] tmp_fu_221_p2;
wire  signed [31:0] cast38_fu_251_p0;
wire   [27:0] div47_cast_fu_236_p4;
wire  signed [31:0] add_fu_272_p1;
wire   [31:0] add_fu_272_p2;
wire   [31:0] empty_fu_266_p2;
wire   [31:0] grp_fu_284_p0;
wire   [31:0] grp_fu_284_p2;
reg    grp_fu_284_ap_start;
wire    grp_fu_284_ap_done;
reg    grp_fu_284_ce;
reg    ap_block_state41_on_subcall_done;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
reg    ap_ST_fsm_state41_blk;
wire   [91:0] bound17_fu_209_p00;
wire   [91:0] bound17_fu_209_p10;
wire   [59:0] bound39_fu_201_p00;
wire   [59:0] bound39_fu_201_p10;
wire   [87:0] bound46_fu_205_p00;
wire   [87:0] bound46_fu_205_p10;
wire   [61:0] bound_fu_213_p00;
wire   [61:0] bound_fu_213_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 41'd1;
#0 grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start_reg = 1'b0;
#0 grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start_reg = 1'b0;
end

top_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start),
    .ap_done(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_done),
    .ap_idle(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_idle),
    .ap_ready(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_ready),
    .m_axi_MM_BUS_AWVALID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWVALID),
    .m_axi_MM_BUS_AWREADY(1'b0),
    .m_axi_MM_BUS_AWADDR(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWADDR),
    .m_axi_MM_BUS_AWID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWID),
    .m_axi_MM_BUS_AWLEN(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWLEN),
    .m_axi_MM_BUS_AWSIZE(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWSIZE),
    .m_axi_MM_BUS_AWBURST(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWBURST),
    .m_axi_MM_BUS_AWLOCK(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWLOCK),
    .m_axi_MM_BUS_AWCACHE(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWCACHE),
    .m_axi_MM_BUS_AWPROT(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWPROT),
    .m_axi_MM_BUS_AWQOS(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWQOS),
    .m_axi_MM_BUS_AWREGION(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWREGION),
    .m_axi_MM_BUS_AWUSER(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_AWUSER),
    .m_axi_MM_BUS_WVALID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WVALID),
    .m_axi_MM_BUS_WREADY(1'b0),
    .m_axi_MM_BUS_WDATA(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WDATA),
    .m_axi_MM_BUS_WSTRB(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WSTRB),
    .m_axi_MM_BUS_WLAST(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WLAST),
    .m_axi_MM_BUS_WID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WID),
    .m_axi_MM_BUS_WUSER(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_WUSER),
    .m_axi_MM_BUS_ARVALID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARVALID),
    .m_axi_MM_BUS_ARREADY(m_axi_MM_BUS_ARREADY),
    .m_axi_MM_BUS_ARADDR(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARADDR),
    .m_axi_MM_BUS_ARID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARID),
    .m_axi_MM_BUS_ARLEN(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARLEN),
    .m_axi_MM_BUS_ARSIZE(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARSIZE),
    .m_axi_MM_BUS_ARBURST(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARBURST),
    .m_axi_MM_BUS_ARLOCK(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARLOCK),
    .m_axi_MM_BUS_ARCACHE(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARCACHE),
    .m_axi_MM_BUS_ARPROT(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARPROT),
    .m_axi_MM_BUS_ARQOS(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARQOS),
    .m_axi_MM_BUS_ARREGION(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARREGION),
    .m_axi_MM_BUS_ARUSER(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARUSER),
    .m_axi_MM_BUS_RVALID(m_axi_MM_BUS_RVALID),
    .m_axi_MM_BUS_RREADY(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_RREADY),
    .m_axi_MM_BUS_RDATA(m_axi_MM_BUS_RDATA),
    .m_axi_MM_BUS_RLAST(m_axi_MM_BUS_RLAST),
    .m_axi_MM_BUS_RID(m_axi_MM_BUS_RID),
    .m_axi_MM_BUS_RFIFONUM(m_axi_MM_BUS_RFIFONUM),
    .m_axi_MM_BUS_RUSER(m_axi_MM_BUS_RUSER),
    .m_axi_MM_BUS_RRESP(m_axi_MM_BUS_RRESP),
    .m_axi_MM_BUS_BVALID(1'b0),
    .m_axi_MM_BUS_BREADY(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_BREADY),
    .m_axi_MM_BUS_BRESP(2'd0),
    .m_axi_MM_BUS_BID(1'd0),
    .m_axi_MM_BUS_BUSER(1'd0),
    .fifo_mm_w_din(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_fifo_mm_w_din),
    .fifo_mm_w_num_data_valid(8'd0),
    .fifo_mm_w_fifo_cap(8'd0),
    .fifo_mm_w_full_n(fifo_mm_w_full_n),
    .fifo_mm_w_write(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_fifo_mm_w_write),
    .bound46(bound46_reg_392),
    .N(N),
    .bound39(bound39_reg_387),
    .MM_Weight(MM_Weight)
);

top_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start),
    .ap_done(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_done),
    .ap_idle(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_idle),
    .ap_ready(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_ready),
    .m_axi_CONV_BUS_AWVALID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWVALID),
    .m_axi_CONV_BUS_AWREADY(1'b0),
    .m_axi_CONV_BUS_AWADDR(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWADDR),
    .m_axi_CONV_BUS_AWID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWID),
    .m_axi_CONV_BUS_AWLEN(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWLEN),
    .m_axi_CONV_BUS_AWSIZE(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWSIZE),
    .m_axi_CONV_BUS_AWBURST(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWBURST),
    .m_axi_CONV_BUS_AWLOCK(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWLOCK),
    .m_axi_CONV_BUS_AWCACHE(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWCACHE),
    .m_axi_CONV_BUS_AWPROT(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWPROT),
    .m_axi_CONV_BUS_AWQOS(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWQOS),
    .m_axi_CONV_BUS_AWREGION(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWREGION),
    .m_axi_CONV_BUS_AWUSER(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_AWUSER),
    .m_axi_CONV_BUS_WVALID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WVALID),
    .m_axi_CONV_BUS_WREADY(1'b0),
    .m_axi_CONV_BUS_WDATA(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WDATA),
    .m_axi_CONV_BUS_WSTRB(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WSTRB),
    .m_axi_CONV_BUS_WLAST(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WLAST),
    .m_axi_CONV_BUS_WID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WID),
    .m_axi_CONV_BUS_WUSER(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_WUSER),
    .m_axi_CONV_BUS_ARVALID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARVALID),
    .m_axi_CONV_BUS_ARREADY(m_axi_CONV_BUS_ARREADY),
    .m_axi_CONV_BUS_ARADDR(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARADDR),
    .m_axi_CONV_BUS_ARID(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARID),
    .m_axi_CONV_BUS_ARLEN(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARLEN),
    .m_axi_CONV_BUS_ARSIZE(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARSIZE),
    .m_axi_CONV_BUS_ARBURST(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARBURST),
    .m_axi_CONV_BUS_ARLOCK(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARLOCK),
    .m_axi_CONV_BUS_ARCACHE(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARCACHE),
    .m_axi_CONV_BUS_ARPROT(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARPROT),
    .m_axi_CONV_BUS_ARQOS(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARQOS),
    .m_axi_CONV_BUS_ARREGION(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARREGION),
    .m_axi_CONV_BUS_ARUSER(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARUSER),
    .m_axi_CONV_BUS_RVALID(m_axi_CONV_BUS_RVALID),
    .m_axi_CONV_BUS_RREADY(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_RREADY),
    .m_axi_CONV_BUS_RDATA(m_axi_CONV_BUS_RDATA),
    .m_axi_CONV_BUS_RLAST(m_axi_CONV_BUS_RLAST),
    .m_axi_CONV_BUS_RID(m_axi_CONV_BUS_RID),
    .m_axi_CONV_BUS_RFIFONUM(m_axi_CONV_BUS_RFIFONUM),
    .m_axi_CONV_BUS_RUSER(m_axi_CONV_BUS_RUSER),
    .m_axi_CONV_BUS_RRESP(m_axi_CONV_BUS_RRESP),
    .m_axi_CONV_BUS_BVALID(1'b0),
    .m_axi_CONV_BUS_BREADY(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_BREADY),
    .m_axi_CONV_BUS_BRESP(2'd0),
    .m_axi_CONV_BUS_BID(1'd0),
    .m_axi_CONV_BUS_BUSER(1'd0),
    .fifo_conv_w_2_din(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_2_din),
    .fifo_conv_w_2_num_data_valid(4'd0),
    .fifo_conv_w_2_fifo_cap(4'd0),
    .fifo_conv_w_2_full_n(fifo_conv_w_2_full_n),
    .fifo_conv_w_2_write(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_2_write),
    .fifo_conv_w_1_din(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_1_din),
    .fifo_conv_w_1_num_data_valid(4'd0),
    .fifo_conv_w_1_fifo_cap(4'd0),
    .fifo_conv_w_1_full_n(fifo_conv_w_1_full_n),
    .fifo_conv_w_1_write(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_1_write),
    .fifo_conv_w_0_din(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_0_din),
    .fifo_conv_w_0_num_data_valid(4'd0),
    .fifo_conv_w_0_fifo_cap(4'd0),
    .fifo_conv_w_0_full_n(fifo_conv_w_0_full_n),
    .fifo_conv_w_0_write(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_0_write),
    .fifo_conv_w_3_din(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_3_din),
    .fifo_conv_w_3_num_data_valid(4'd0),
    .fifo_conv_w_3_fifo_cap(4'd0),
    .fifo_conv_w_3_full_n(fifo_conv_w_3_full_n),
    .fifo_conv_w_3_write(grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_3_write),
    .bound17(bound17_reg_439),
    .zext_ln229(empty_1053_reg_444),
    .bound4(tmp_s_reg_434),
    .and_ln(and_ln_reg_423),
    .bound(bound_reg_429),
    .mul14(mul14_reg_402),
    .Conv_Weight(Conv_Weight)
);

top_mul_28ns_32ns_60_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 28 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 60 ))
mul_28ns_32ns_60_1_1_U739(
    .din0(bound39_fu_201_p0),
    .din1(bound39_fu_201_p1),
    .dout(bound39_fu_201_p2)
);

top_mul_28ns_60ns_88_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 28 ),
    .din1_WIDTH( 60 ),
    .dout_WIDTH( 88 ))
mul_28ns_60ns_88_1_1_U740(
    .din0(bound46_fu_205_p0),
    .din1(bound46_fu_205_p1),
    .dout(bound46_fu_205_p2)
);

top_mul_28ns_64ns_92_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 28 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 92 ))
mul_28ns_64ns_92_1_1_U741(
    .din0(bound17_fu_209_p0),
    .din1(bound17_fu_209_p1),
    .dout(bound17_fu_209_p2)
);

top_mul_32ns_30ns_62_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 62 ))
mul_32ns_30ns_62_1_1_U742(
    .din0(bound_fu_213_p0),
    .din1(bound_fu_213_p1),
    .dout(bound_fu_213_p2)
);

top_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U743(
    .din0(tmp_fu_221_p2),
    .din1(K),
    .dout(mul14_fu_217_p2)
);

top_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U744(
    .din0(K),
    .din1(N),
    .dout(tmp_fu_221_p2)
);

top_udiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
udiv_32ns_32ns_32_36_seq_1_U745(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_284_ap_start),
    .done(grp_fu_284_ap_done),
    .din0(grp_fu_284_p0),
    .din1(S),
    .ce(grp_fu_284_ce),
    .dout(grp_fu_284_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state41_on_subcall_done) & (1'b1 == ap_CS_fsm_state41))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state40)) begin
            grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start_reg <= 1'b1;
        end else if ((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_ready == 1'b1)) begin
            grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start_reg <= 1'b1;
        end else if ((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_ready == 1'b1)) begin
            grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        add8_reg_413 <= add8_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        and_ln_reg_423[29 : 2] <= and_ln_fu_311_p3[29 : 2];
        bound17_reg_439 <= bound17_fu_209_p2;
        bound_reg_429 <= bound_fu_213_p2;
        icmp_reg_418 <= icmp_fu_306_p2;
        tmp_s_reg_434[63 : 2] <= tmp_s_fu_327_p3[63 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        bound39_reg_387 <= bound39_fu_201_p2;
        bound46_reg_392 <= bound46_fu_205_p2;
        trunc_ln_reg_382 <= {{M[31:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        empty_1053_reg_444[29 : 2] <= empty_1053_fu_344_p3[29 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mul14_reg_402 <= mul14_fu_217_p2;
        tmp_12_reg_407 <= {{mul14_fu_217_p2[31:4]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state41_on_subcall_done)) begin
        ap_ST_fsm_state41_blk = 1'b1;
    end else begin
        ap_ST_fsm_state41_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state41_on_subcall_done) & (1'b1 == ap_CS_fsm_state41))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state41_on_subcall_done) & (1'b1 == ap_CS_fsm_state41))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((mode == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
        fifo_conv_w_0_write = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_0_write;
    end else begin
        fifo_conv_w_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((mode == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
        fifo_conv_w_1_write = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_1_write;
    end else begin
        fifo_conv_w_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((mode == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
        fifo_conv_w_2_write = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_2_write;
    end else begin
        fifo_conv_w_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((mode == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
        fifo_conv_w_3_write = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_3_write;
    end else begin
        fifo_conv_w_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_mm_w_write = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_fifo_mm_w_write;
    end else begin
        fifo_mm_w_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (mode == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_284_ap_start = 1'b1;
    end else begin
        grp_fu_284_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39))) begin
        grp_fu_284_ce = 1'b0;
    end else begin
        grp_fu_284_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) | ((mode == 1'd1) & (1'b1 == ap_CS_fsm_state41)))) begin
        m_axi_CONV_BUS_ARVALID = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARVALID;
    end else begin
        m_axi_CONV_BUS_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) | ((mode == 1'd1) & (1'b1 == ap_CS_fsm_state41)))) begin
        m_axi_CONV_BUS_RREADY = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_RREADY;
    end else begin
        m_axi_CONV_BUS_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_MM_BUS_ARVALID = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARVALID;
    end else begin
        m_axi_MM_BUS_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_MM_BUS_RREADY = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_RREADY;
    end else begin
        m_axi_MM_BUS_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_c68_blk_n = mode_c68_full_n;
    end else begin
        mode_c68_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_c68_write = 1'b1;
    end else begin
        mode_c68_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_c69_blk_n = mode_c69_full_n;
    end else begin
        mode_c69_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_c69_write = 1'b1;
    end else begin
        mode_c69_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (mode == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b0 == ap_block_state1) & (mode_read_read_fu_98_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            if (((1'b0 == ap_block_state41_on_subcall_done) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add8_fu_300_p2 = (grp_fu_284_p2 + 32'd1);

assign add_fu_272_p1 = K;

assign add_fu_272_p2 = ($signed(R) - $signed(add_fu_272_p1));

assign and_ln_fu_311_p3 = {{tmp_12_reg_407}, {2'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | (mode_c69_full_n == 1'b0) | (mode_c68_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state41_on_subcall_done = ((grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_done == 1'b0) & (mode == 1'd1));
end

assign bound17_fu_209_p0 = bound17_fu_209_p00;

assign bound17_fu_209_p00 = trunc_ln_reg_382;

assign bound17_fu_209_p1 = bound17_fu_209_p10;

assign bound17_fu_209_p10 = tmp_s_fu_327_p3;

assign bound39_fu_201_p0 = bound39_fu_201_p00;

assign bound39_fu_201_p00 = trunc_ln_fu_226_p4;

assign bound39_fu_201_p1 = bound39_fu_201_p10;

assign bound39_fu_201_p10 = $unsigned(cast38_fu_251_p0);

assign bound46_fu_205_p0 = bound46_fu_205_p00;

assign bound46_fu_205_p00 = div47_cast_fu_236_p4;

assign bound46_fu_205_p1 = bound46_fu_205_p10;

assign bound46_fu_205_p10 = bound39_fu_201_p2;

assign bound_fu_213_p0 = bound_fu_213_p00;

assign bound_fu_213_p00 = add8_reg_413;

assign bound_fu_213_p1 = bound_fu_213_p10;

assign bound_fu_213_p10 = and_ln_fu_311_p3;

assign cast38_fu_251_p0 = N;

assign div47_cast_fu_236_p4 = {{R[31:4]}};

assign empty_1053_fu_344_p3 = ((icmp_reg_418[0:0] == 1'b1) ? and_ln_reg_423 : 30'd0);

assign empty_fu_266_p2 = P << 32'd1;

assign fifo_conv_w_0_din = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_0_din;

assign fifo_conv_w_1_din = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_1_din;

assign fifo_conv_w_2_din = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_2_din;

assign fifo_conv_w_3_din = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_fifo_conv_w_3_din;

assign fifo_mm_w_din = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_fifo_mm_w_din;

assign grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_ap_start_reg;

assign grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_ap_start_reg;

assign grp_fu_284_p0 = (add_fu_272_p2 + empty_fu_266_p2);

assign icmp_fu_306_p2 = ((tmp_12_reg_407 != 28'd0) ? 1'b1 : 1'b0);

assign m_axi_CONV_BUS_ARADDR = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARADDR;

assign m_axi_CONV_BUS_ARBURST = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARBURST;

assign m_axi_CONV_BUS_ARCACHE = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARCACHE;

assign m_axi_CONV_BUS_ARID = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARID;

assign m_axi_CONV_BUS_ARLEN = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARLEN;

assign m_axi_CONV_BUS_ARLOCK = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARLOCK;

assign m_axi_CONV_BUS_ARPROT = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARPROT;

assign m_axi_CONV_BUS_ARQOS = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARQOS;

assign m_axi_CONV_BUS_ARREGION = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARREGION;

assign m_axi_CONV_BUS_ARSIZE = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARSIZE;

assign m_axi_CONV_BUS_ARUSER = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_229_1_VITIS_LOOP_232_2_VITIS_LOOP_234_s_fu_180_m_axi_CONV_BUS_ARUSER;

assign m_axi_CONV_BUS_AWADDR = 64'd0;

assign m_axi_CONV_BUS_AWBURST = 2'd0;

assign m_axi_CONV_BUS_AWCACHE = 4'd0;

assign m_axi_CONV_BUS_AWID = 1'd0;

assign m_axi_CONV_BUS_AWLEN = 32'd0;

assign m_axi_CONV_BUS_AWLOCK = 2'd0;

assign m_axi_CONV_BUS_AWPROT = 3'd0;

assign m_axi_CONV_BUS_AWQOS = 4'd0;

assign m_axi_CONV_BUS_AWREGION = 4'd0;

assign m_axi_CONV_BUS_AWSIZE = 3'd0;

assign m_axi_CONV_BUS_AWUSER = 1'd0;

assign m_axi_CONV_BUS_AWVALID = 1'b0;

assign m_axi_CONV_BUS_BREADY = 1'b0;

assign m_axi_CONV_BUS_WDATA = 512'd0;

assign m_axi_CONV_BUS_WID = 1'd0;

assign m_axi_CONV_BUS_WLAST = 1'b0;

assign m_axi_CONV_BUS_WSTRB = 64'd0;

assign m_axi_CONV_BUS_WUSER = 1'd0;

assign m_axi_CONV_BUS_WVALID = 1'b0;

assign m_axi_MM_BUS_ARADDR = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARADDR;

assign m_axi_MM_BUS_ARBURST = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARBURST;

assign m_axi_MM_BUS_ARCACHE = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARCACHE;

assign m_axi_MM_BUS_ARID = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARID;

assign m_axi_MM_BUS_ARLEN = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARLEN;

assign m_axi_MM_BUS_ARLOCK = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARLOCK;

assign m_axi_MM_BUS_ARPROT = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARPROT;

assign m_axi_MM_BUS_ARQOS = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARQOS;

assign m_axi_MM_BUS_ARREGION = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARREGION;

assign m_axi_MM_BUS_ARSIZE = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARSIZE;

assign m_axi_MM_BUS_ARUSER = grp_ConvertWeightToStream_Pipeline_VITIS_LOOP_251_5_VITIS_LOOP_254_6_VITIS_LOOP_257_s_fu_168_m_axi_MM_BUS_ARUSER;

assign m_axi_MM_BUS_AWADDR = 64'd0;

assign m_axi_MM_BUS_AWBURST = 2'd0;

assign m_axi_MM_BUS_AWCACHE = 4'd0;

assign m_axi_MM_BUS_AWID = 1'd0;

assign m_axi_MM_BUS_AWLEN = 32'd0;

assign m_axi_MM_BUS_AWLOCK = 2'd0;

assign m_axi_MM_BUS_AWPROT = 3'd0;

assign m_axi_MM_BUS_AWQOS = 4'd0;

assign m_axi_MM_BUS_AWREGION = 4'd0;

assign m_axi_MM_BUS_AWSIZE = 3'd0;

assign m_axi_MM_BUS_AWUSER = 1'd0;

assign m_axi_MM_BUS_AWVALID = 1'b0;

assign m_axi_MM_BUS_BREADY = 1'b0;

assign m_axi_MM_BUS_WDATA = 512'd0;

assign m_axi_MM_BUS_WID = 1'd0;

assign m_axi_MM_BUS_WLAST = 1'b0;

assign m_axi_MM_BUS_WSTRB = 64'd0;

assign m_axi_MM_BUS_WUSER = 1'd0;

assign m_axi_MM_BUS_WVALID = 1'b0;

assign mode_c68_din = mode;

assign mode_c69_din = mode;

assign mode_read_read_fu_98_p2 = mode;

assign tmp_s_fu_327_p3 = {{bound_fu_213_p2}, {2'd0}};

assign trunc_ln_fu_226_p4 = {{M[31:4]}};

always @ (posedge ap_clk) begin
    and_ln_reg_423[1:0] <= 2'b00;
    tmp_s_reg_434[1:0] <= 2'b00;
    empty_1053_reg_444[1:0] <= 2'b00;
end

endmodule //top_ConvertWeightToStream
