// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_MuxWeightStream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        Conv_SA_W_dout,
        Conv_SA_W_num_data_valid,
        Conv_SA_W_fifo_cap,
        Conv_SA_W_empty_n,
        Conv_SA_W_read,
        Conv_SA_W_1_dout,
        Conv_SA_W_1_num_data_valid,
        Conv_SA_W_1_fifo_cap,
        Conv_SA_W_1_empty_n,
        Conv_SA_W_1_read,
        Conv_SA_W_2_dout,
        Conv_SA_W_2_num_data_valid,
        Conv_SA_W_2_fifo_cap,
        Conv_SA_W_2_empty_n,
        Conv_SA_W_2_read,
        Conv_SA_W_3_dout,
        Conv_SA_W_3_num_data_valid,
        Conv_SA_W_3_fifo_cap,
        Conv_SA_W_3_empty_n,
        Conv_SA_W_3_read,
        Conv_SA_W_4_dout,
        Conv_SA_W_4_num_data_valid,
        Conv_SA_W_4_fifo_cap,
        Conv_SA_W_4_empty_n,
        Conv_SA_W_4_read,
        Conv_SA_W_5_dout,
        Conv_SA_W_5_num_data_valid,
        Conv_SA_W_5_fifo_cap,
        Conv_SA_W_5_empty_n,
        Conv_SA_W_5_read,
        Conv_SA_W_6_dout,
        Conv_SA_W_6_num_data_valid,
        Conv_SA_W_6_fifo_cap,
        Conv_SA_W_6_empty_n,
        Conv_SA_W_6_read,
        Conv_SA_W_7_dout,
        Conv_SA_W_7_num_data_valid,
        Conv_SA_W_7_fifo_cap,
        Conv_SA_W_7_empty_n,
        Conv_SA_W_7_read,
        Conv_SA_W_8_dout,
        Conv_SA_W_8_num_data_valid,
        Conv_SA_W_8_fifo_cap,
        Conv_SA_W_8_empty_n,
        Conv_SA_W_8_read,
        Conv_SA_W_9_dout,
        Conv_SA_W_9_num_data_valid,
        Conv_SA_W_9_fifo_cap,
        Conv_SA_W_9_empty_n,
        Conv_SA_W_9_read,
        Conv_SA_W_10_dout,
        Conv_SA_W_10_num_data_valid,
        Conv_SA_W_10_fifo_cap,
        Conv_SA_W_10_empty_n,
        Conv_SA_W_10_read,
        Conv_SA_W_11_dout,
        Conv_SA_W_11_num_data_valid,
        Conv_SA_W_11_fifo_cap,
        Conv_SA_W_11_empty_n,
        Conv_SA_W_11_read,
        Conv_SA_W_12_dout,
        Conv_SA_W_12_num_data_valid,
        Conv_SA_W_12_fifo_cap,
        Conv_SA_W_12_empty_n,
        Conv_SA_W_12_read,
        Conv_SA_W_13_dout,
        Conv_SA_W_13_num_data_valid,
        Conv_SA_W_13_fifo_cap,
        Conv_SA_W_13_empty_n,
        Conv_SA_W_13_read,
        Conv_SA_W_14_dout,
        Conv_SA_W_14_num_data_valid,
        Conv_SA_W_14_fifo_cap,
        Conv_SA_W_14_empty_n,
        Conv_SA_W_14_read,
        Conv_SA_W_15_dout,
        Conv_SA_W_15_num_data_valid,
        Conv_SA_W_15_fifo_cap,
        Conv_SA_W_15_empty_n,
        Conv_SA_W_15_read,
        MM_SA_W_dout,
        MM_SA_W_num_data_valid,
        MM_SA_W_fifo_cap,
        MM_SA_W_empty_n,
        MM_SA_W_read,
        MM_SA_W_1_dout,
        MM_SA_W_1_num_data_valid,
        MM_SA_W_1_fifo_cap,
        MM_SA_W_1_empty_n,
        MM_SA_W_1_read,
        MM_SA_W_2_dout,
        MM_SA_W_2_num_data_valid,
        MM_SA_W_2_fifo_cap,
        MM_SA_W_2_empty_n,
        MM_SA_W_2_read,
        MM_SA_W_3_dout,
        MM_SA_W_3_num_data_valid,
        MM_SA_W_3_fifo_cap,
        MM_SA_W_3_empty_n,
        MM_SA_W_3_read,
        MM_SA_W_4_dout,
        MM_SA_W_4_num_data_valid,
        MM_SA_W_4_fifo_cap,
        MM_SA_W_4_empty_n,
        MM_SA_W_4_read,
        MM_SA_W_5_dout,
        MM_SA_W_5_num_data_valid,
        MM_SA_W_5_fifo_cap,
        MM_SA_W_5_empty_n,
        MM_SA_W_5_read,
        MM_SA_W_6_dout,
        MM_SA_W_6_num_data_valid,
        MM_SA_W_6_fifo_cap,
        MM_SA_W_6_empty_n,
        MM_SA_W_6_read,
        MM_SA_W_7_dout,
        MM_SA_W_7_num_data_valid,
        MM_SA_W_7_fifo_cap,
        MM_SA_W_7_empty_n,
        MM_SA_W_7_read,
        MM_SA_W_8_dout,
        MM_SA_W_8_num_data_valid,
        MM_SA_W_8_fifo_cap,
        MM_SA_W_8_empty_n,
        MM_SA_W_8_read,
        MM_SA_W_9_dout,
        MM_SA_W_9_num_data_valid,
        MM_SA_W_9_fifo_cap,
        MM_SA_W_9_empty_n,
        MM_SA_W_9_read,
        MM_SA_W_10_dout,
        MM_SA_W_10_num_data_valid,
        MM_SA_W_10_fifo_cap,
        MM_SA_W_10_empty_n,
        MM_SA_W_10_read,
        MM_SA_W_11_dout,
        MM_SA_W_11_num_data_valid,
        MM_SA_W_11_fifo_cap,
        MM_SA_W_11_empty_n,
        MM_SA_W_11_read,
        MM_SA_W_12_dout,
        MM_SA_W_12_num_data_valid,
        MM_SA_W_12_fifo_cap,
        MM_SA_W_12_empty_n,
        MM_SA_W_12_read,
        MM_SA_W_13_dout,
        MM_SA_W_13_num_data_valid,
        MM_SA_W_13_fifo_cap,
        MM_SA_W_13_empty_n,
        MM_SA_W_13_read,
        MM_SA_W_14_dout,
        MM_SA_W_14_num_data_valid,
        MM_SA_W_14_fifo_cap,
        MM_SA_W_14_empty_n,
        MM_SA_W_14_read,
        MM_SA_W_15_dout,
        MM_SA_W_15_num_data_valid,
        MM_SA_W_15_fifo_cap,
        MM_SA_W_15_empty_n,
        MM_SA_W_15_read,
        fifo_SA_W_din,
        fifo_SA_W_num_data_valid,
        fifo_SA_W_fifo_cap,
        fifo_SA_W_full_n,
        fifo_SA_W_write,
        fifo_SA_W_1_din,
        fifo_SA_W_1_num_data_valid,
        fifo_SA_W_1_fifo_cap,
        fifo_SA_W_1_full_n,
        fifo_SA_W_1_write,
        fifo_SA_W_2_din,
        fifo_SA_W_2_num_data_valid,
        fifo_SA_W_2_fifo_cap,
        fifo_SA_W_2_full_n,
        fifo_SA_W_2_write,
        fifo_SA_W_3_din,
        fifo_SA_W_3_num_data_valid,
        fifo_SA_W_3_fifo_cap,
        fifo_SA_W_3_full_n,
        fifo_SA_W_3_write,
        fifo_SA_W_4_din,
        fifo_SA_W_4_num_data_valid,
        fifo_SA_W_4_fifo_cap,
        fifo_SA_W_4_full_n,
        fifo_SA_W_4_write,
        fifo_SA_W_5_din,
        fifo_SA_W_5_num_data_valid,
        fifo_SA_W_5_fifo_cap,
        fifo_SA_W_5_full_n,
        fifo_SA_W_5_write,
        fifo_SA_W_6_din,
        fifo_SA_W_6_num_data_valid,
        fifo_SA_W_6_fifo_cap,
        fifo_SA_W_6_full_n,
        fifo_SA_W_6_write,
        fifo_SA_W_7_din,
        fifo_SA_W_7_num_data_valid,
        fifo_SA_W_7_fifo_cap,
        fifo_SA_W_7_full_n,
        fifo_SA_W_7_write,
        fifo_SA_W_8_din,
        fifo_SA_W_8_num_data_valid,
        fifo_SA_W_8_fifo_cap,
        fifo_SA_W_8_full_n,
        fifo_SA_W_8_write,
        fifo_SA_W_9_din,
        fifo_SA_W_9_num_data_valid,
        fifo_SA_W_9_fifo_cap,
        fifo_SA_W_9_full_n,
        fifo_SA_W_9_write,
        fifo_SA_W_10_din,
        fifo_SA_W_10_num_data_valid,
        fifo_SA_W_10_fifo_cap,
        fifo_SA_W_10_full_n,
        fifo_SA_W_10_write,
        fifo_SA_W_11_din,
        fifo_SA_W_11_num_data_valid,
        fifo_SA_W_11_fifo_cap,
        fifo_SA_W_11_full_n,
        fifo_SA_W_11_write,
        fifo_SA_W_12_din,
        fifo_SA_W_12_num_data_valid,
        fifo_SA_W_12_fifo_cap,
        fifo_SA_W_12_full_n,
        fifo_SA_W_12_write,
        fifo_SA_W_13_din,
        fifo_SA_W_13_num_data_valid,
        fifo_SA_W_13_fifo_cap,
        fifo_SA_W_13_full_n,
        fifo_SA_W_13_write,
        fifo_SA_W_14_din,
        fifo_SA_W_14_num_data_valid,
        fifo_SA_W_14_fifo_cap,
        fifo_SA_W_14_full_n,
        fifo_SA_W_14_write,
        fifo_SA_W_15_din,
        fifo_SA_W_15_num_data_valid,
        fifo_SA_W_15_fifo_cap,
        fifo_SA_W_15_full_n,
        fifo_SA_W_15_write,
        num_w_sa_loc_dout,
        num_w_sa_loc_num_data_valid,
        num_w_sa_loc_fifo_cap,
        num_w_sa_loc_empty_n,
        num_w_sa_loc_read,
        mode_dout,
        mode_num_data_valid,
        mode_fifo_cap,
        mode_empty_n,
        mode_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] Conv_SA_W_dout;
input  [3:0] Conv_SA_W_num_data_valid;
input  [3:0] Conv_SA_W_fifo_cap;
input   Conv_SA_W_empty_n;
output   Conv_SA_W_read;
input  [127:0] Conv_SA_W_1_dout;
input  [3:0] Conv_SA_W_1_num_data_valid;
input  [3:0] Conv_SA_W_1_fifo_cap;
input   Conv_SA_W_1_empty_n;
output   Conv_SA_W_1_read;
input  [127:0] Conv_SA_W_2_dout;
input  [3:0] Conv_SA_W_2_num_data_valid;
input  [3:0] Conv_SA_W_2_fifo_cap;
input   Conv_SA_W_2_empty_n;
output   Conv_SA_W_2_read;
input  [127:0] Conv_SA_W_3_dout;
input  [3:0] Conv_SA_W_3_num_data_valid;
input  [3:0] Conv_SA_W_3_fifo_cap;
input   Conv_SA_W_3_empty_n;
output   Conv_SA_W_3_read;
input  [127:0] Conv_SA_W_4_dout;
input  [3:0] Conv_SA_W_4_num_data_valid;
input  [3:0] Conv_SA_W_4_fifo_cap;
input   Conv_SA_W_4_empty_n;
output   Conv_SA_W_4_read;
input  [127:0] Conv_SA_W_5_dout;
input  [3:0] Conv_SA_W_5_num_data_valid;
input  [3:0] Conv_SA_W_5_fifo_cap;
input   Conv_SA_W_5_empty_n;
output   Conv_SA_W_5_read;
input  [127:0] Conv_SA_W_6_dout;
input  [3:0] Conv_SA_W_6_num_data_valid;
input  [3:0] Conv_SA_W_6_fifo_cap;
input   Conv_SA_W_6_empty_n;
output   Conv_SA_W_6_read;
input  [127:0] Conv_SA_W_7_dout;
input  [3:0] Conv_SA_W_7_num_data_valid;
input  [3:0] Conv_SA_W_7_fifo_cap;
input   Conv_SA_W_7_empty_n;
output   Conv_SA_W_7_read;
input  [127:0] Conv_SA_W_8_dout;
input  [3:0] Conv_SA_W_8_num_data_valid;
input  [3:0] Conv_SA_W_8_fifo_cap;
input   Conv_SA_W_8_empty_n;
output   Conv_SA_W_8_read;
input  [127:0] Conv_SA_W_9_dout;
input  [3:0] Conv_SA_W_9_num_data_valid;
input  [3:0] Conv_SA_W_9_fifo_cap;
input   Conv_SA_W_9_empty_n;
output   Conv_SA_W_9_read;
input  [127:0] Conv_SA_W_10_dout;
input  [3:0] Conv_SA_W_10_num_data_valid;
input  [3:0] Conv_SA_W_10_fifo_cap;
input   Conv_SA_W_10_empty_n;
output   Conv_SA_W_10_read;
input  [127:0] Conv_SA_W_11_dout;
input  [3:0] Conv_SA_W_11_num_data_valid;
input  [3:0] Conv_SA_W_11_fifo_cap;
input   Conv_SA_W_11_empty_n;
output   Conv_SA_W_11_read;
input  [127:0] Conv_SA_W_12_dout;
input  [3:0] Conv_SA_W_12_num_data_valid;
input  [3:0] Conv_SA_W_12_fifo_cap;
input   Conv_SA_W_12_empty_n;
output   Conv_SA_W_12_read;
input  [127:0] Conv_SA_W_13_dout;
input  [3:0] Conv_SA_W_13_num_data_valid;
input  [3:0] Conv_SA_W_13_fifo_cap;
input   Conv_SA_W_13_empty_n;
output   Conv_SA_W_13_read;
input  [127:0] Conv_SA_W_14_dout;
input  [3:0] Conv_SA_W_14_num_data_valid;
input  [3:0] Conv_SA_W_14_fifo_cap;
input   Conv_SA_W_14_empty_n;
output   Conv_SA_W_14_read;
input  [127:0] Conv_SA_W_15_dout;
input  [3:0] Conv_SA_W_15_num_data_valid;
input  [3:0] Conv_SA_W_15_fifo_cap;
input   Conv_SA_W_15_empty_n;
output   Conv_SA_W_15_read;
input  [127:0] MM_SA_W_dout;
input  [2:0] MM_SA_W_num_data_valid;
input  [2:0] MM_SA_W_fifo_cap;
input   MM_SA_W_empty_n;
output   MM_SA_W_read;
input  [127:0] MM_SA_W_1_dout;
input  [2:0] MM_SA_W_1_num_data_valid;
input  [2:0] MM_SA_W_1_fifo_cap;
input   MM_SA_W_1_empty_n;
output   MM_SA_W_1_read;
input  [127:0] MM_SA_W_2_dout;
input  [2:0] MM_SA_W_2_num_data_valid;
input  [2:0] MM_SA_W_2_fifo_cap;
input   MM_SA_W_2_empty_n;
output   MM_SA_W_2_read;
input  [127:0] MM_SA_W_3_dout;
input  [2:0] MM_SA_W_3_num_data_valid;
input  [2:0] MM_SA_W_3_fifo_cap;
input   MM_SA_W_3_empty_n;
output   MM_SA_W_3_read;
input  [127:0] MM_SA_W_4_dout;
input  [2:0] MM_SA_W_4_num_data_valid;
input  [2:0] MM_SA_W_4_fifo_cap;
input   MM_SA_W_4_empty_n;
output   MM_SA_W_4_read;
input  [127:0] MM_SA_W_5_dout;
input  [2:0] MM_SA_W_5_num_data_valid;
input  [2:0] MM_SA_W_5_fifo_cap;
input   MM_SA_W_5_empty_n;
output   MM_SA_W_5_read;
input  [127:0] MM_SA_W_6_dout;
input  [2:0] MM_SA_W_6_num_data_valid;
input  [2:0] MM_SA_W_6_fifo_cap;
input   MM_SA_W_6_empty_n;
output   MM_SA_W_6_read;
input  [127:0] MM_SA_W_7_dout;
input  [2:0] MM_SA_W_7_num_data_valid;
input  [2:0] MM_SA_W_7_fifo_cap;
input   MM_SA_W_7_empty_n;
output   MM_SA_W_7_read;
input  [127:0] MM_SA_W_8_dout;
input  [2:0] MM_SA_W_8_num_data_valid;
input  [2:0] MM_SA_W_8_fifo_cap;
input   MM_SA_W_8_empty_n;
output   MM_SA_W_8_read;
input  [127:0] MM_SA_W_9_dout;
input  [2:0] MM_SA_W_9_num_data_valid;
input  [2:0] MM_SA_W_9_fifo_cap;
input   MM_SA_W_9_empty_n;
output   MM_SA_W_9_read;
input  [127:0] MM_SA_W_10_dout;
input  [2:0] MM_SA_W_10_num_data_valid;
input  [2:0] MM_SA_W_10_fifo_cap;
input   MM_SA_W_10_empty_n;
output   MM_SA_W_10_read;
input  [127:0] MM_SA_W_11_dout;
input  [2:0] MM_SA_W_11_num_data_valid;
input  [2:0] MM_SA_W_11_fifo_cap;
input   MM_SA_W_11_empty_n;
output   MM_SA_W_11_read;
input  [127:0] MM_SA_W_12_dout;
input  [2:0] MM_SA_W_12_num_data_valid;
input  [2:0] MM_SA_W_12_fifo_cap;
input   MM_SA_W_12_empty_n;
output   MM_SA_W_12_read;
input  [127:0] MM_SA_W_13_dout;
input  [2:0] MM_SA_W_13_num_data_valid;
input  [2:0] MM_SA_W_13_fifo_cap;
input   MM_SA_W_13_empty_n;
output   MM_SA_W_13_read;
input  [127:0] MM_SA_W_14_dout;
input  [2:0] MM_SA_W_14_num_data_valid;
input  [2:0] MM_SA_W_14_fifo_cap;
input   MM_SA_W_14_empty_n;
output   MM_SA_W_14_read;
input  [127:0] MM_SA_W_15_dout;
input  [2:0] MM_SA_W_15_num_data_valid;
input  [2:0] MM_SA_W_15_fifo_cap;
input   MM_SA_W_15_empty_n;
output   MM_SA_W_15_read;
output  [127:0] fifo_SA_W_din;
input  [3:0] fifo_SA_W_num_data_valid;
input  [3:0] fifo_SA_W_fifo_cap;
input   fifo_SA_W_full_n;
output   fifo_SA_W_write;
output  [127:0] fifo_SA_W_1_din;
input  [3:0] fifo_SA_W_1_num_data_valid;
input  [3:0] fifo_SA_W_1_fifo_cap;
input   fifo_SA_W_1_full_n;
output   fifo_SA_W_1_write;
output  [127:0] fifo_SA_W_2_din;
input  [3:0] fifo_SA_W_2_num_data_valid;
input  [3:0] fifo_SA_W_2_fifo_cap;
input   fifo_SA_W_2_full_n;
output   fifo_SA_W_2_write;
output  [127:0] fifo_SA_W_3_din;
input  [3:0] fifo_SA_W_3_num_data_valid;
input  [3:0] fifo_SA_W_3_fifo_cap;
input   fifo_SA_W_3_full_n;
output   fifo_SA_W_3_write;
output  [127:0] fifo_SA_W_4_din;
input  [3:0] fifo_SA_W_4_num_data_valid;
input  [3:0] fifo_SA_W_4_fifo_cap;
input   fifo_SA_W_4_full_n;
output   fifo_SA_W_4_write;
output  [127:0] fifo_SA_W_5_din;
input  [3:0] fifo_SA_W_5_num_data_valid;
input  [3:0] fifo_SA_W_5_fifo_cap;
input   fifo_SA_W_5_full_n;
output   fifo_SA_W_5_write;
output  [127:0] fifo_SA_W_6_din;
input  [3:0] fifo_SA_W_6_num_data_valid;
input  [3:0] fifo_SA_W_6_fifo_cap;
input   fifo_SA_W_6_full_n;
output   fifo_SA_W_6_write;
output  [127:0] fifo_SA_W_7_din;
input  [3:0] fifo_SA_W_7_num_data_valid;
input  [3:0] fifo_SA_W_7_fifo_cap;
input   fifo_SA_W_7_full_n;
output   fifo_SA_W_7_write;
output  [127:0] fifo_SA_W_8_din;
input  [3:0] fifo_SA_W_8_num_data_valid;
input  [3:0] fifo_SA_W_8_fifo_cap;
input   fifo_SA_W_8_full_n;
output   fifo_SA_W_8_write;
output  [127:0] fifo_SA_W_9_din;
input  [3:0] fifo_SA_W_9_num_data_valid;
input  [3:0] fifo_SA_W_9_fifo_cap;
input   fifo_SA_W_9_full_n;
output   fifo_SA_W_9_write;
output  [127:0] fifo_SA_W_10_din;
input  [3:0] fifo_SA_W_10_num_data_valid;
input  [3:0] fifo_SA_W_10_fifo_cap;
input   fifo_SA_W_10_full_n;
output   fifo_SA_W_10_write;
output  [127:0] fifo_SA_W_11_din;
input  [3:0] fifo_SA_W_11_num_data_valid;
input  [3:0] fifo_SA_W_11_fifo_cap;
input   fifo_SA_W_11_full_n;
output   fifo_SA_W_11_write;
output  [127:0] fifo_SA_W_12_din;
input  [3:0] fifo_SA_W_12_num_data_valid;
input  [3:0] fifo_SA_W_12_fifo_cap;
input   fifo_SA_W_12_full_n;
output   fifo_SA_W_12_write;
output  [127:0] fifo_SA_W_13_din;
input  [3:0] fifo_SA_W_13_num_data_valid;
input  [3:0] fifo_SA_W_13_fifo_cap;
input   fifo_SA_W_13_full_n;
output   fifo_SA_W_13_write;
output  [127:0] fifo_SA_W_14_din;
input  [3:0] fifo_SA_W_14_num_data_valid;
input  [3:0] fifo_SA_W_14_fifo_cap;
input   fifo_SA_W_14_full_n;
output   fifo_SA_W_14_write;
output  [127:0] fifo_SA_W_15_din;
input  [3:0] fifo_SA_W_15_num_data_valid;
input  [3:0] fifo_SA_W_15_fifo_cap;
input   fifo_SA_W_15_full_n;
output   fifo_SA_W_15_write;
input  [29:0] num_w_sa_loc_dout;
input  [2:0] num_w_sa_loc_num_data_valid;
input  [2:0] num_w_sa_loc_fifo_cap;
input   num_w_sa_loc_empty_n;
output   num_w_sa_loc_read;
input  [0:0] mode_dout;
input  [2:0] mode_num_data_valid;
input  [2:0] mode_fifo_cap;
input   mode_empty_n;
output   mode_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Conv_SA_W_read;
reg Conv_SA_W_1_read;
reg Conv_SA_W_2_read;
reg Conv_SA_W_3_read;
reg Conv_SA_W_4_read;
reg Conv_SA_W_5_read;
reg Conv_SA_W_6_read;
reg Conv_SA_W_7_read;
reg Conv_SA_W_8_read;
reg Conv_SA_W_9_read;
reg Conv_SA_W_10_read;
reg Conv_SA_W_11_read;
reg Conv_SA_W_12_read;
reg Conv_SA_W_13_read;
reg Conv_SA_W_14_read;
reg Conv_SA_W_15_read;
reg MM_SA_W_read;
reg MM_SA_W_1_read;
reg MM_SA_W_2_read;
reg MM_SA_W_3_read;
reg MM_SA_W_4_read;
reg MM_SA_W_5_read;
reg MM_SA_W_6_read;
reg MM_SA_W_7_read;
reg MM_SA_W_8_read;
reg MM_SA_W_9_read;
reg MM_SA_W_10_read;
reg MM_SA_W_11_read;
reg MM_SA_W_12_read;
reg MM_SA_W_13_read;
reg MM_SA_W_14_read;
reg MM_SA_W_15_read;
reg fifo_SA_W_write;
reg fifo_SA_W_1_write;
reg fifo_SA_W_2_write;
reg fifo_SA_W_3_write;
reg fifo_SA_W_4_write;
reg fifo_SA_W_5_write;
reg fifo_SA_W_6_write;
reg fifo_SA_W_7_write;
reg fifo_SA_W_8_write;
reg fifo_SA_W_9_write;
reg fifo_SA_W_10_write;
reg fifo_SA_W_11_write;
reg fifo_SA_W_12_write;
reg fifo_SA_W_13_write;
reg fifo_SA_W_14_write;
reg fifo_SA_W_15_write;
reg num_w_sa_loc_read;
reg mode_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    num_w_sa_loc_blk_n;
reg    mode_blk_n;
reg   [0:0] mode_4_reg_242;
reg    ap_block_state1;
reg   [29:0] num_w_sa_reg_247;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_done;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_idle;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_ready;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_1_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_2_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_3_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_4_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_5_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_6_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_7_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_8_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_9_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_10_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_11_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_12_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_13_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_14_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_15_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_1_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_2_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_3_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_4_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_5_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_6_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_7_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_8_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_9_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_10_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_11_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_12_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_13_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_14_read;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_15_read;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_1_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_1_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_2_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_2_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_3_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_3_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_4_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_4_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_5_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_5_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_6_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_6_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_7_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_7_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_8_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_8_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_9_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_9_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_10_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_10_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_11_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_11_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_12_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_12_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_13_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_13_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_14_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_14_write;
wire   [127:0] grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_15_din;
wire    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_15_write;
reg    grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start_reg = 1'b0;
end

top_MuxWeightStream_Pipeline_VITIS_LOOP_314_1 grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start),
    .ap_done(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_done),
    .ap_idle(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_idle),
    .ap_ready(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_ready),
    .MM_SA_W_dout(MM_SA_W_dout),
    .MM_SA_W_num_data_valid(3'd0),
    .MM_SA_W_fifo_cap(3'd0),
    .MM_SA_W_empty_n(MM_SA_W_empty_n),
    .MM_SA_W_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_read),
    .MM_SA_W_1_dout(MM_SA_W_1_dout),
    .MM_SA_W_1_num_data_valid(3'd0),
    .MM_SA_W_1_fifo_cap(3'd0),
    .MM_SA_W_1_empty_n(MM_SA_W_1_empty_n),
    .MM_SA_W_1_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_1_read),
    .MM_SA_W_2_dout(MM_SA_W_2_dout),
    .MM_SA_W_2_num_data_valid(3'd0),
    .MM_SA_W_2_fifo_cap(3'd0),
    .MM_SA_W_2_empty_n(MM_SA_W_2_empty_n),
    .MM_SA_W_2_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_2_read),
    .MM_SA_W_3_dout(MM_SA_W_3_dout),
    .MM_SA_W_3_num_data_valid(3'd0),
    .MM_SA_W_3_fifo_cap(3'd0),
    .MM_SA_W_3_empty_n(MM_SA_W_3_empty_n),
    .MM_SA_W_3_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_3_read),
    .MM_SA_W_4_dout(MM_SA_W_4_dout),
    .MM_SA_W_4_num_data_valid(3'd0),
    .MM_SA_W_4_fifo_cap(3'd0),
    .MM_SA_W_4_empty_n(MM_SA_W_4_empty_n),
    .MM_SA_W_4_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_4_read),
    .MM_SA_W_5_dout(MM_SA_W_5_dout),
    .MM_SA_W_5_num_data_valid(3'd0),
    .MM_SA_W_5_fifo_cap(3'd0),
    .MM_SA_W_5_empty_n(MM_SA_W_5_empty_n),
    .MM_SA_W_5_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_5_read),
    .MM_SA_W_6_dout(MM_SA_W_6_dout),
    .MM_SA_W_6_num_data_valid(3'd0),
    .MM_SA_W_6_fifo_cap(3'd0),
    .MM_SA_W_6_empty_n(MM_SA_W_6_empty_n),
    .MM_SA_W_6_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_6_read),
    .MM_SA_W_7_dout(MM_SA_W_7_dout),
    .MM_SA_W_7_num_data_valid(3'd0),
    .MM_SA_W_7_fifo_cap(3'd0),
    .MM_SA_W_7_empty_n(MM_SA_W_7_empty_n),
    .MM_SA_W_7_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_7_read),
    .MM_SA_W_8_dout(MM_SA_W_8_dout),
    .MM_SA_W_8_num_data_valid(3'd0),
    .MM_SA_W_8_fifo_cap(3'd0),
    .MM_SA_W_8_empty_n(MM_SA_W_8_empty_n),
    .MM_SA_W_8_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_8_read),
    .MM_SA_W_9_dout(MM_SA_W_9_dout),
    .MM_SA_W_9_num_data_valid(3'd0),
    .MM_SA_W_9_fifo_cap(3'd0),
    .MM_SA_W_9_empty_n(MM_SA_W_9_empty_n),
    .MM_SA_W_9_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_9_read),
    .MM_SA_W_10_dout(MM_SA_W_10_dout),
    .MM_SA_W_10_num_data_valid(3'd0),
    .MM_SA_W_10_fifo_cap(3'd0),
    .MM_SA_W_10_empty_n(MM_SA_W_10_empty_n),
    .MM_SA_W_10_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_10_read),
    .MM_SA_W_11_dout(MM_SA_W_11_dout),
    .MM_SA_W_11_num_data_valid(3'd0),
    .MM_SA_W_11_fifo_cap(3'd0),
    .MM_SA_W_11_empty_n(MM_SA_W_11_empty_n),
    .MM_SA_W_11_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_11_read),
    .MM_SA_W_12_dout(MM_SA_W_12_dout),
    .MM_SA_W_12_num_data_valid(3'd0),
    .MM_SA_W_12_fifo_cap(3'd0),
    .MM_SA_W_12_empty_n(MM_SA_W_12_empty_n),
    .MM_SA_W_12_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_12_read),
    .MM_SA_W_13_dout(MM_SA_W_13_dout),
    .MM_SA_W_13_num_data_valid(3'd0),
    .MM_SA_W_13_fifo_cap(3'd0),
    .MM_SA_W_13_empty_n(MM_SA_W_13_empty_n),
    .MM_SA_W_13_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_13_read),
    .MM_SA_W_14_dout(MM_SA_W_14_dout),
    .MM_SA_W_14_num_data_valid(3'd0),
    .MM_SA_W_14_fifo_cap(3'd0),
    .MM_SA_W_14_empty_n(MM_SA_W_14_empty_n),
    .MM_SA_W_14_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_14_read),
    .MM_SA_W_15_dout(MM_SA_W_15_dout),
    .MM_SA_W_15_num_data_valid(3'd0),
    .MM_SA_W_15_fifo_cap(3'd0),
    .MM_SA_W_15_empty_n(MM_SA_W_15_empty_n),
    .MM_SA_W_15_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_15_read),
    .Conv_SA_W_dout(Conv_SA_W_dout),
    .Conv_SA_W_num_data_valid(4'd0),
    .Conv_SA_W_fifo_cap(4'd0),
    .Conv_SA_W_empty_n(Conv_SA_W_empty_n),
    .Conv_SA_W_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_read),
    .Conv_SA_W_1_dout(Conv_SA_W_1_dout),
    .Conv_SA_W_1_num_data_valid(4'd0),
    .Conv_SA_W_1_fifo_cap(4'd0),
    .Conv_SA_W_1_empty_n(Conv_SA_W_1_empty_n),
    .Conv_SA_W_1_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_1_read),
    .Conv_SA_W_2_dout(Conv_SA_W_2_dout),
    .Conv_SA_W_2_num_data_valid(4'd0),
    .Conv_SA_W_2_fifo_cap(4'd0),
    .Conv_SA_W_2_empty_n(Conv_SA_W_2_empty_n),
    .Conv_SA_W_2_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_2_read),
    .Conv_SA_W_3_dout(Conv_SA_W_3_dout),
    .Conv_SA_W_3_num_data_valid(4'd0),
    .Conv_SA_W_3_fifo_cap(4'd0),
    .Conv_SA_W_3_empty_n(Conv_SA_W_3_empty_n),
    .Conv_SA_W_3_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_3_read),
    .Conv_SA_W_4_dout(Conv_SA_W_4_dout),
    .Conv_SA_W_4_num_data_valid(4'd0),
    .Conv_SA_W_4_fifo_cap(4'd0),
    .Conv_SA_W_4_empty_n(Conv_SA_W_4_empty_n),
    .Conv_SA_W_4_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_4_read),
    .Conv_SA_W_5_dout(Conv_SA_W_5_dout),
    .Conv_SA_W_5_num_data_valid(4'd0),
    .Conv_SA_W_5_fifo_cap(4'd0),
    .Conv_SA_W_5_empty_n(Conv_SA_W_5_empty_n),
    .Conv_SA_W_5_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_5_read),
    .Conv_SA_W_6_dout(Conv_SA_W_6_dout),
    .Conv_SA_W_6_num_data_valid(4'd0),
    .Conv_SA_W_6_fifo_cap(4'd0),
    .Conv_SA_W_6_empty_n(Conv_SA_W_6_empty_n),
    .Conv_SA_W_6_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_6_read),
    .Conv_SA_W_7_dout(Conv_SA_W_7_dout),
    .Conv_SA_W_7_num_data_valid(4'd0),
    .Conv_SA_W_7_fifo_cap(4'd0),
    .Conv_SA_W_7_empty_n(Conv_SA_W_7_empty_n),
    .Conv_SA_W_7_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_7_read),
    .Conv_SA_W_8_dout(Conv_SA_W_8_dout),
    .Conv_SA_W_8_num_data_valid(4'd0),
    .Conv_SA_W_8_fifo_cap(4'd0),
    .Conv_SA_W_8_empty_n(Conv_SA_W_8_empty_n),
    .Conv_SA_W_8_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_8_read),
    .Conv_SA_W_9_dout(Conv_SA_W_9_dout),
    .Conv_SA_W_9_num_data_valid(4'd0),
    .Conv_SA_W_9_fifo_cap(4'd0),
    .Conv_SA_W_9_empty_n(Conv_SA_W_9_empty_n),
    .Conv_SA_W_9_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_9_read),
    .Conv_SA_W_10_dout(Conv_SA_W_10_dout),
    .Conv_SA_W_10_num_data_valid(4'd0),
    .Conv_SA_W_10_fifo_cap(4'd0),
    .Conv_SA_W_10_empty_n(Conv_SA_W_10_empty_n),
    .Conv_SA_W_10_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_10_read),
    .Conv_SA_W_11_dout(Conv_SA_W_11_dout),
    .Conv_SA_W_11_num_data_valid(4'd0),
    .Conv_SA_W_11_fifo_cap(4'd0),
    .Conv_SA_W_11_empty_n(Conv_SA_W_11_empty_n),
    .Conv_SA_W_11_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_11_read),
    .Conv_SA_W_12_dout(Conv_SA_W_12_dout),
    .Conv_SA_W_12_num_data_valid(4'd0),
    .Conv_SA_W_12_fifo_cap(4'd0),
    .Conv_SA_W_12_empty_n(Conv_SA_W_12_empty_n),
    .Conv_SA_W_12_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_12_read),
    .Conv_SA_W_13_dout(Conv_SA_W_13_dout),
    .Conv_SA_W_13_num_data_valid(4'd0),
    .Conv_SA_W_13_fifo_cap(4'd0),
    .Conv_SA_W_13_empty_n(Conv_SA_W_13_empty_n),
    .Conv_SA_W_13_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_13_read),
    .Conv_SA_W_14_dout(Conv_SA_W_14_dout),
    .Conv_SA_W_14_num_data_valid(4'd0),
    .Conv_SA_W_14_fifo_cap(4'd0),
    .Conv_SA_W_14_empty_n(Conv_SA_W_14_empty_n),
    .Conv_SA_W_14_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_14_read),
    .Conv_SA_W_15_dout(Conv_SA_W_15_dout),
    .Conv_SA_W_15_num_data_valid(4'd0),
    .Conv_SA_W_15_fifo_cap(4'd0),
    .Conv_SA_W_15_empty_n(Conv_SA_W_15_empty_n),
    .Conv_SA_W_15_read(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_15_read),
    .fifo_SA_W_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_din),
    .fifo_SA_W_num_data_valid(4'd0),
    .fifo_SA_W_fifo_cap(4'd0),
    .fifo_SA_W_full_n(fifo_SA_W_full_n),
    .fifo_SA_W_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_write),
    .fifo_SA_W_1_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_1_din),
    .fifo_SA_W_1_num_data_valid(4'd0),
    .fifo_SA_W_1_fifo_cap(4'd0),
    .fifo_SA_W_1_full_n(fifo_SA_W_1_full_n),
    .fifo_SA_W_1_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_1_write),
    .fifo_SA_W_2_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_2_din),
    .fifo_SA_W_2_num_data_valid(4'd0),
    .fifo_SA_W_2_fifo_cap(4'd0),
    .fifo_SA_W_2_full_n(fifo_SA_W_2_full_n),
    .fifo_SA_W_2_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_2_write),
    .fifo_SA_W_3_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_3_din),
    .fifo_SA_W_3_num_data_valid(4'd0),
    .fifo_SA_W_3_fifo_cap(4'd0),
    .fifo_SA_W_3_full_n(fifo_SA_W_3_full_n),
    .fifo_SA_W_3_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_3_write),
    .fifo_SA_W_4_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_4_din),
    .fifo_SA_W_4_num_data_valid(4'd0),
    .fifo_SA_W_4_fifo_cap(4'd0),
    .fifo_SA_W_4_full_n(fifo_SA_W_4_full_n),
    .fifo_SA_W_4_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_4_write),
    .fifo_SA_W_5_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_5_din),
    .fifo_SA_W_5_num_data_valid(4'd0),
    .fifo_SA_W_5_fifo_cap(4'd0),
    .fifo_SA_W_5_full_n(fifo_SA_W_5_full_n),
    .fifo_SA_W_5_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_5_write),
    .fifo_SA_W_6_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_6_din),
    .fifo_SA_W_6_num_data_valid(4'd0),
    .fifo_SA_W_6_fifo_cap(4'd0),
    .fifo_SA_W_6_full_n(fifo_SA_W_6_full_n),
    .fifo_SA_W_6_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_6_write),
    .fifo_SA_W_7_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_7_din),
    .fifo_SA_W_7_num_data_valid(4'd0),
    .fifo_SA_W_7_fifo_cap(4'd0),
    .fifo_SA_W_7_full_n(fifo_SA_W_7_full_n),
    .fifo_SA_W_7_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_7_write),
    .fifo_SA_W_8_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_8_din),
    .fifo_SA_W_8_num_data_valid(4'd0),
    .fifo_SA_W_8_fifo_cap(4'd0),
    .fifo_SA_W_8_full_n(fifo_SA_W_8_full_n),
    .fifo_SA_W_8_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_8_write),
    .fifo_SA_W_9_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_9_din),
    .fifo_SA_W_9_num_data_valid(4'd0),
    .fifo_SA_W_9_fifo_cap(4'd0),
    .fifo_SA_W_9_full_n(fifo_SA_W_9_full_n),
    .fifo_SA_W_9_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_9_write),
    .fifo_SA_W_10_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_10_din),
    .fifo_SA_W_10_num_data_valid(4'd0),
    .fifo_SA_W_10_fifo_cap(4'd0),
    .fifo_SA_W_10_full_n(fifo_SA_W_10_full_n),
    .fifo_SA_W_10_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_10_write),
    .fifo_SA_W_11_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_11_din),
    .fifo_SA_W_11_num_data_valid(4'd0),
    .fifo_SA_W_11_fifo_cap(4'd0),
    .fifo_SA_W_11_full_n(fifo_SA_W_11_full_n),
    .fifo_SA_W_11_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_11_write),
    .fifo_SA_W_12_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_12_din),
    .fifo_SA_W_12_num_data_valid(4'd0),
    .fifo_SA_W_12_fifo_cap(4'd0),
    .fifo_SA_W_12_full_n(fifo_SA_W_12_full_n),
    .fifo_SA_W_12_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_12_write),
    .fifo_SA_W_13_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_13_din),
    .fifo_SA_W_13_num_data_valid(4'd0),
    .fifo_SA_W_13_fifo_cap(4'd0),
    .fifo_SA_W_13_full_n(fifo_SA_W_13_full_n),
    .fifo_SA_W_13_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_13_write),
    .fifo_SA_W_14_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_14_din),
    .fifo_SA_W_14_num_data_valid(4'd0),
    .fifo_SA_W_14_fifo_cap(4'd0),
    .fifo_SA_W_14_full_n(fifo_SA_W_14_full_n),
    .fifo_SA_W_14_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_14_write),
    .fifo_SA_W_15_din(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_15_din),
    .fifo_SA_W_15_num_data_valid(4'd0),
    .fifo_SA_W_15_fifo_cap(4'd0),
    .fifo_SA_W_15_full_n(fifo_SA_W_15_full_n),
    .fifo_SA_W_15_write(grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_15_write),
    .num_w_sa(num_w_sa_reg_247),
    .mode_4(mode_4_reg_242)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start_reg <= 1'b1;
        end else if ((grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_ready == 1'b1)) begin
            grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_4_reg_242 <= mode_dout;
        num_w_sa_reg_247 <= num_w_sa_loc_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_10_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_10_read;
    end else begin
        Conv_SA_W_10_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_11_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_11_read;
    end else begin
        Conv_SA_W_11_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_12_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_12_read;
    end else begin
        Conv_SA_W_12_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_13_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_13_read;
    end else begin
        Conv_SA_W_13_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_14_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_14_read;
    end else begin
        Conv_SA_W_14_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_15_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_15_read;
    end else begin
        Conv_SA_W_15_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_1_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_1_read;
    end else begin
        Conv_SA_W_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_2_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_2_read;
    end else begin
        Conv_SA_W_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_3_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_3_read;
    end else begin
        Conv_SA_W_3_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_4_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_4_read;
    end else begin
        Conv_SA_W_4_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_5_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_5_read;
    end else begin
        Conv_SA_W_5_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_6_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_6_read;
    end else begin
        Conv_SA_W_6_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_7_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_7_read;
    end else begin
        Conv_SA_W_7_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_8_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_8_read;
    end else begin
        Conv_SA_W_8_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_9_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_9_read;
    end else begin
        Conv_SA_W_9_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Conv_SA_W_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_Conv_SA_W_read;
    end else begin
        Conv_SA_W_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_10_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_10_read;
    end else begin
        MM_SA_W_10_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_11_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_11_read;
    end else begin
        MM_SA_W_11_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_12_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_12_read;
    end else begin
        MM_SA_W_12_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_13_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_13_read;
    end else begin
        MM_SA_W_13_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_14_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_14_read;
    end else begin
        MM_SA_W_14_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_15_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_15_read;
    end else begin
        MM_SA_W_15_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_1_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_1_read;
    end else begin
        MM_SA_W_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_2_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_2_read;
    end else begin
        MM_SA_W_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_3_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_3_read;
    end else begin
        MM_SA_W_3_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_4_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_4_read;
    end else begin
        MM_SA_W_4_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_5_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_5_read;
    end else begin
        MM_SA_W_5_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_6_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_6_read;
    end else begin
        MM_SA_W_6_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_7_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_7_read;
    end else begin
        MM_SA_W_7_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_8_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_8_read;
    end else begin
        MM_SA_W_8_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_9_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_9_read;
    end else begin
        MM_SA_W_9_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        MM_SA_W_read = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_MM_SA_W_read;
    end else begin
        MM_SA_W_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_10_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_10_write;
    end else begin
        fifo_SA_W_10_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_11_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_11_write;
    end else begin
        fifo_SA_W_11_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_12_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_12_write;
    end else begin
        fifo_SA_W_12_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_13_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_13_write;
    end else begin
        fifo_SA_W_13_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_14_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_14_write;
    end else begin
        fifo_SA_W_14_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_15_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_15_write;
    end else begin
        fifo_SA_W_15_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_1_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_1_write;
    end else begin
        fifo_SA_W_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_2_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_2_write;
    end else begin
        fifo_SA_W_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_3_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_3_write;
    end else begin
        fifo_SA_W_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_4_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_4_write;
    end else begin
        fifo_SA_W_4_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_5_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_5_write;
    end else begin
        fifo_SA_W_5_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_6_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_6_write;
    end else begin
        fifo_SA_W_6_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_7_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_7_write;
    end else begin
        fifo_SA_W_7_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_8_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_8_write;
    end else begin
        fifo_SA_W_8_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_9_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_9_write;
    end else begin
        fifo_SA_W_9_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_SA_W_write = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_write;
    end else begin
        fifo_SA_W_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_blk_n = mode_empty_n;
    end else begin
        mode_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_read = 1'b1;
    end else begin
        mode_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_w_sa_loc_blk_n = num_w_sa_loc_empty_n;
    end else begin
        num_w_sa_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        num_w_sa_loc_read = 1'b1;
    end else begin
        num_w_sa_loc_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (mode_empty_n == 1'b0) | (num_w_sa_loc_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign fifo_SA_W_10_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_10_din;

assign fifo_SA_W_11_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_11_din;

assign fifo_SA_W_12_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_12_din;

assign fifo_SA_W_13_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_13_din;

assign fifo_SA_W_14_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_14_din;

assign fifo_SA_W_15_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_15_din;

assign fifo_SA_W_1_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_1_din;

assign fifo_SA_W_2_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_2_din;

assign fifo_SA_W_3_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_3_din;

assign fifo_SA_W_4_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_4_din;

assign fifo_SA_W_5_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_5_din;

assign fifo_SA_W_6_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_6_din;

assign fifo_SA_W_7_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_7_din;

assign fifo_SA_W_8_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_8_din;

assign fifo_SA_W_9_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_9_din;

assign fifo_SA_W_din = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_fifo_SA_W_din;

assign grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start = grp_MuxWeightStream_Pipeline_VITIS_LOOP_314_1_fu_140_ap_start_reg;

endmodule //top_MuxWeightStream
